steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.http',
        '-t',
        'europe-west1-docker.pkg.dev/lazervault/lazervault/lazervault-golang-http:latest',
        '.',
      ]
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/lazervault/lazervault/lazervault-golang-http:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'lazervault-golang-http',
        '--image',
        'europe-west1-docker.pkg.dev/lazervault/lazervault/lazervault-golang-http:latest',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--port',
        '7878',
        '--quiet',
        '--allow-unauthenticated',
      ]
images:
  - 'europe-west1-docker.pkg.dev/lazervault/lazervault/lazervault-golang-http:latest'
