// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: account_card.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountCardService_CreateVirtualCard_FullMethodName       = "/pb.AccountCardService/CreateVirtualCard"
	AccountCardService_CreateDisposableCard_FullMethodName    = "/pb.AccountCardService/CreateDisposableCard"
	AccountCardService_GetUserCards_FullMethodName            = "/pb.AccountCardService/GetUserCards"
	AccountCardService_GetCardDetails_FullMethodName          = "/pb.AccountCardService/GetCardDetails"
	AccountCardService_FreezeCard_FullMethodName              = "/pb.AccountCardService/FreezeCard"
	AccountCardService_UnfreezeCard_FullMethodName            = "/pb.AccountCardService/UnfreezeCard"
	AccountCardService_CancelCard_FullMethodName              = "/pb.AccountCardService/CancelCard"
	AccountCardService_UpdateCardNickname_FullMethodName      = "/pb.AccountCardService/UpdateCardNickname"
	AccountCardService_UpdateCardSpendingLimit_FullMethodName = "/pb.AccountCardService/UpdateCardSpendingLimit"
	AccountCardService_GetCardTransactions_FullMethodName     = "/pb.AccountCardService/GetCardTransactions"
	AccountCardService_SetDefaultCard_FullMethodName          = "/pb.AccountCardService/SetDefaultCard"
)

// AccountCardServiceClient is the client API for AccountCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountCard Service Definition
type AccountCardServiceClient interface {
	// Create a new virtual card
	CreateVirtualCard(ctx context.Context, in *CreateVirtualCardRequest, opts ...grpc.CallOption) (*CreateVirtualCardResponse, error)
	// Create a new disposable card
	CreateDisposableCard(ctx context.Context, in *CreateDisposableCardRequest, opts ...grpc.CallOption) (*CreateDisposableCardResponse, error)
	// Get all cards for the authenticated user
	GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error)
	// Get detailed information about a specific card
	GetCardDetails(ctx context.Context, in *GetCardDetailsRequest, opts ...grpc.CallOption) (*GetCardDetailsResponse, error)
	// Freeze a card
	FreezeCard(ctx context.Context, in *FreezeCardRequest, opts ...grpc.CallOption) (*FreezeCardResponse, error)
	// Unfreeze a card
	UnfreezeCard(ctx context.Context, in *UnfreezeCardRequest, opts ...grpc.CallOption) (*UnfreezeCardResponse, error)
	// Cancel a card permanently
	CancelCard(ctx context.Context, in *CancelCardRequest, opts ...grpc.CallOption) (*CancelCardResponse, error)
	// Update card nickname
	UpdateCardNickname(ctx context.Context, in *UpdateCardNicknameRequest, opts ...grpc.CallOption) (*UpdateCardNicknameResponse, error)
	// Update spending limit for disposable cards
	UpdateCardSpendingLimit(ctx context.Context, in *UpdateCardSpendingLimitRequest, opts ...grpc.CallOption) (*UpdateCardSpendingLimitResponse, error)
	// Get card transactions
	GetCardTransactions(ctx context.Context, in *GetCardTransactionsRequest, opts ...grpc.CallOption) (*GetCardTransactionsResponse, error)
	// Set default card
	SetDefaultCard(ctx context.Context, in *SetDefaultCardRequest, opts ...grpc.CallOption) (*SetDefaultCardResponse, error)
}

type accountCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountCardServiceClient(cc grpc.ClientConnInterface) AccountCardServiceClient {
	return &accountCardServiceClient{cc}
}

func (c *accountCardServiceClient) CreateVirtualCard(ctx context.Context, in *CreateVirtualCardRequest, opts ...grpc.CallOption) (*CreateVirtualCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVirtualCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_CreateVirtualCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) CreateDisposableCard(ctx context.Context, in *CreateDisposableCardRequest, opts ...grpc.CallOption) (*CreateDisposableCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDisposableCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_CreateDisposableCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCardsResponse)
	err := c.cc.Invoke(ctx, AccountCardService_GetUserCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) GetCardDetails(ctx context.Context, in *GetCardDetailsRequest, opts ...grpc.CallOption) (*GetCardDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardDetailsResponse)
	err := c.cc.Invoke(ctx, AccountCardService_GetCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) FreezeCard(ctx context.Context, in *FreezeCardRequest, opts ...grpc.CallOption) (*FreezeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_FreezeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) UnfreezeCard(ctx context.Context, in *UnfreezeCardRequest, opts ...grpc.CallOption) (*UnfreezeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_UnfreezeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) CancelCard(ctx context.Context, in *CancelCardRequest, opts ...grpc.CallOption) (*CancelCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_CancelCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) UpdateCardNickname(ctx context.Context, in *UpdateCardNicknameRequest, opts ...grpc.CallOption) (*UpdateCardNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCardNicknameResponse)
	err := c.cc.Invoke(ctx, AccountCardService_UpdateCardNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) UpdateCardSpendingLimit(ctx context.Context, in *UpdateCardSpendingLimitRequest, opts ...grpc.CallOption) (*UpdateCardSpendingLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCardSpendingLimitResponse)
	err := c.cc.Invoke(ctx, AccountCardService_UpdateCardSpendingLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) GetCardTransactions(ctx context.Context, in *GetCardTransactionsRequest, opts ...grpc.CallOption) (*GetCardTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardTransactionsResponse)
	err := c.cc.Invoke(ctx, AccountCardService_GetCardTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) SetDefaultCard(ctx context.Context, in *SetDefaultCardRequest, opts ...grpc.CallOption) (*SetDefaultCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_SetDefaultCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCardServiceServer is the server API for AccountCardService service.
// All implementations must embed UnimplementedAccountCardServiceServer
// for forward compatibility.
//
// AccountCard Service Definition
type AccountCardServiceServer interface {
	// Create a new virtual card
	CreateVirtualCard(context.Context, *CreateVirtualCardRequest) (*CreateVirtualCardResponse, error)
	// Create a new disposable card
	CreateDisposableCard(context.Context, *CreateDisposableCardRequest) (*CreateDisposableCardResponse, error)
	// Get all cards for the authenticated user
	GetUserCards(context.Context, *GetUserCardsRequest) (*GetUserCardsResponse, error)
	// Get detailed information about a specific card
	GetCardDetails(context.Context, *GetCardDetailsRequest) (*GetCardDetailsResponse, error)
	// Freeze a card
	FreezeCard(context.Context, *FreezeCardRequest) (*FreezeCardResponse, error)
	// Unfreeze a card
	UnfreezeCard(context.Context, *UnfreezeCardRequest) (*UnfreezeCardResponse, error)
	// Cancel a card permanently
	CancelCard(context.Context, *CancelCardRequest) (*CancelCardResponse, error)
	// Update card nickname
	UpdateCardNickname(context.Context, *UpdateCardNicknameRequest) (*UpdateCardNicknameResponse, error)
	// Update spending limit for disposable cards
	UpdateCardSpendingLimit(context.Context, *UpdateCardSpendingLimitRequest) (*UpdateCardSpendingLimitResponse, error)
	// Get card transactions
	GetCardTransactions(context.Context, *GetCardTransactionsRequest) (*GetCardTransactionsResponse, error)
	// Set default card
	SetDefaultCard(context.Context, *SetDefaultCardRequest) (*SetDefaultCardResponse, error)
	mustEmbedUnimplementedAccountCardServiceServer()
}

// UnimplementedAccountCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountCardServiceServer struct{}

func (UnimplementedAccountCardServiceServer) CreateVirtualCard(context.Context, *CreateVirtualCardRequest) (*CreateVirtualCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVirtualCard not implemented")
}
func (UnimplementedAccountCardServiceServer) CreateDisposableCard(context.Context, *CreateDisposableCardRequest) (*CreateDisposableCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDisposableCard not implemented")
}
func (UnimplementedAccountCardServiceServer) GetUserCards(context.Context, *GetUserCardsRequest) (*GetUserCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCards not implemented")
}
func (UnimplementedAccountCardServiceServer) GetCardDetails(context.Context, *GetCardDetailsRequest) (*GetCardDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardDetails not implemented")
}
func (UnimplementedAccountCardServiceServer) FreezeCard(context.Context, *FreezeCardRequest) (*FreezeCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeCard not implemented")
}
func (UnimplementedAccountCardServiceServer) UnfreezeCard(context.Context, *UnfreezeCardRequest) (*UnfreezeCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfreezeCard not implemented")
}
func (UnimplementedAccountCardServiceServer) CancelCard(context.Context, *CancelCardRequest) (*CancelCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCard not implemented")
}
func (UnimplementedAccountCardServiceServer) UpdateCardNickname(context.Context, *UpdateCardNicknameRequest) (*UpdateCardNicknameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCardNickname not implemented")
}
func (UnimplementedAccountCardServiceServer) UpdateCardSpendingLimit(context.Context, *UpdateCardSpendingLimitRequest) (*UpdateCardSpendingLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCardSpendingLimit not implemented")
}
func (UnimplementedAccountCardServiceServer) GetCardTransactions(context.Context, *GetCardTransactionsRequest) (*GetCardTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardTransactions not implemented")
}
func (UnimplementedAccountCardServiceServer) SetDefaultCard(context.Context, *SetDefaultCardRequest) (*SetDefaultCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultCard not implemented")
}
func (UnimplementedAccountCardServiceServer) mustEmbedUnimplementedAccountCardServiceServer() {}
func (UnimplementedAccountCardServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountCardServiceServer will
// result in compilation errors.
type UnsafeAccountCardServiceServer interface {
	mustEmbedUnimplementedAccountCardServiceServer()
}

func RegisterAccountCardServiceServer(s grpc.ServiceRegistrar, srv AccountCardServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountCardService_ServiceDesc, srv)
}

func _AccountCardService_CreateVirtualCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVirtualCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).CreateVirtualCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_CreateVirtualCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).CreateVirtualCard(ctx, req.(*CreateVirtualCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_CreateDisposableCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDisposableCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).CreateDisposableCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_CreateDisposableCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).CreateDisposableCard(ctx, req.(*CreateDisposableCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_GetUserCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).GetUserCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_GetUserCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).GetUserCards(ctx, req.(*GetUserCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_GetCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).GetCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_GetCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).GetCardDetails(ctx, req.(*GetCardDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_FreezeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).FreezeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_FreezeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).FreezeCard(ctx, req.(*FreezeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_UnfreezeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).UnfreezeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_UnfreezeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).UnfreezeCard(ctx, req.(*UnfreezeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_CancelCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).CancelCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_CancelCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).CancelCard(ctx, req.(*CancelCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_UpdateCardNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).UpdateCardNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_UpdateCardNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).UpdateCardNickname(ctx, req.(*UpdateCardNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_UpdateCardSpendingLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardSpendingLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).UpdateCardSpendingLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_UpdateCardSpendingLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).UpdateCardSpendingLimit(ctx, req.(*UpdateCardSpendingLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_GetCardTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).GetCardTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_GetCardTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).GetCardTransactions(ctx, req.(*GetCardTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_SetDefaultCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).SetDefaultCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_SetDefaultCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).SetDefaultCard(ctx, req.(*SetDefaultCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountCardService_ServiceDesc is the grpc.ServiceDesc for AccountCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AccountCardService",
	HandlerType: (*AccountCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVirtualCard",
			Handler:    _AccountCardService_CreateVirtualCard_Handler,
		},
		{
			MethodName: "CreateDisposableCard",
			Handler:    _AccountCardService_CreateDisposableCard_Handler,
		},
		{
			MethodName: "GetUserCards",
			Handler:    _AccountCardService_GetUserCards_Handler,
		},
		{
			MethodName: "GetCardDetails",
			Handler:    _AccountCardService_GetCardDetails_Handler,
		},
		{
			MethodName: "FreezeCard",
			Handler:    _AccountCardService_FreezeCard_Handler,
		},
		{
			MethodName: "UnfreezeCard",
			Handler:    _AccountCardService_UnfreezeCard_Handler,
		},
		{
			MethodName: "CancelCard",
			Handler:    _AccountCardService_CancelCard_Handler,
		},
		{
			MethodName: "UpdateCardNickname",
			Handler:    _AccountCardService_UpdateCardNickname_Handler,
		},
		{
			MethodName: "UpdateCardSpendingLimit",
			Handler:    _AccountCardService_UpdateCardSpendingLimit_Handler,
		},
		{
			MethodName: "GetCardTransactions",
			Handler:    _AccountCardService_GetCardTransactions_Handler,
		},
		{
			MethodName: "SetDefaultCard",
			Handler:    _AccountCardService_SetDefaultCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_card.proto",
}
