// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Invoice Payment Status Enum - comprehensive status for all invoice payment scenarios
type InvoicePaymentStatus int32

const (
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_PENDING        InvoicePaymentStatus = 0
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_PROCESSING     InvoicePaymentStatus = 1
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_COMPLETED      InvoicePaymentStatus = 2
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_FAILED         InvoicePaymentStatus = 3
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_CANCELLED      InvoicePaymentStatus = 4
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_PARTIALLY_PAID InvoicePaymentStatus = 5
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_REFUNDED       InvoicePaymentStatus = 6
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_DISPUTED       InvoicePaymentStatus = 7
	InvoicePaymentStatus_INVOICE_PAYMENT_STATUS_OVERDUE        InvoicePaymentStatus = 8
)

// Enum value maps for InvoicePaymentStatus.
var (
	InvoicePaymentStatus_name = map[int32]string{
		0: "INVOICE_PAYMENT_STATUS_PENDING",
		1: "INVOICE_PAYMENT_STATUS_PROCESSING",
		2: "INVOICE_PAYMENT_STATUS_COMPLETED",
		3: "INVOICE_PAYMENT_STATUS_FAILED",
		4: "INVOICE_PAYMENT_STATUS_CANCELLED",
		5: "INVOICE_PAYMENT_STATUS_PARTIALLY_PAID",
		6: "INVOICE_PAYMENT_STATUS_REFUNDED",
		7: "INVOICE_PAYMENT_STATUS_DISPUTED",
		8: "INVOICE_PAYMENT_STATUS_OVERDUE",
	}
	InvoicePaymentStatus_value = map[string]int32{
		"INVOICE_PAYMENT_STATUS_PENDING":        0,
		"INVOICE_PAYMENT_STATUS_PROCESSING":     1,
		"INVOICE_PAYMENT_STATUS_COMPLETED":      2,
		"INVOICE_PAYMENT_STATUS_FAILED":         3,
		"INVOICE_PAYMENT_STATUS_CANCELLED":      4,
		"INVOICE_PAYMENT_STATUS_PARTIALLY_PAID": 5,
		"INVOICE_PAYMENT_STATUS_REFUNDED":       6,
		"INVOICE_PAYMENT_STATUS_DISPUTED":       7,
		"INVOICE_PAYMENT_STATUS_OVERDUE":        8,
	}
)

func (x InvoicePaymentStatus) Enum() *InvoicePaymentStatus {
	p := new(InvoicePaymentStatus)
	*p = x
	return p
}

func (x InvoicePaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoicePaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (InvoicePaymentStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x InvoicePaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoicePaymentStatus.Descriptor instead.
func (InvoicePaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Payment Method Type Enum
type PaymentMethodType int32

const (
	PaymentMethodType_PAYMENT_METHOD_TYPE_ACCOUNT_BALANCE PaymentMethodType = 0
	PaymentMethodType_PAYMENT_METHOD_TYPE_CREDIT_CARD     PaymentMethodType = 1
	PaymentMethodType_PAYMENT_METHOD_TYPE_DEBIT_CARD      PaymentMethodType = 2
	PaymentMethodType_PAYMENT_METHOD_TYPE_PAYPAL          PaymentMethodType = 3
	PaymentMethodType_PAYMENT_METHOD_TYPE_APPLE_PAY       PaymentMethodType = 4
	PaymentMethodType_PAYMENT_METHOD_TYPE_GOOGLE_PAY      PaymentMethodType = 5
	PaymentMethodType_PAYMENT_METHOD_TYPE_BITCOIN         PaymentMethodType = 6
	PaymentMethodType_PAYMENT_METHOD_TYPE_ETHEREUM        PaymentMethodType = 7
	PaymentMethodType_PAYMENT_METHOD_TYPE_USDC            PaymentMethodType = 8
	PaymentMethodType_PAYMENT_METHOD_TYPE_BANK_TRANSFER   PaymentMethodType = 9
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0: "PAYMENT_METHOD_TYPE_ACCOUNT_BALANCE",
		1: "PAYMENT_METHOD_TYPE_CREDIT_CARD",
		2: "PAYMENT_METHOD_TYPE_DEBIT_CARD",
		3: "PAYMENT_METHOD_TYPE_PAYPAL",
		4: "PAYMENT_METHOD_TYPE_APPLE_PAY",
		5: "PAYMENT_METHOD_TYPE_GOOGLE_PAY",
		6: "PAYMENT_METHOD_TYPE_BITCOIN",
		7: "PAYMENT_METHOD_TYPE_ETHEREUM",
		8: "PAYMENT_METHOD_TYPE_USDC",
		9: "PAYMENT_METHOD_TYPE_BANK_TRANSFER",
	}
	PaymentMethodType_value = map[string]int32{
		"PAYMENT_METHOD_TYPE_ACCOUNT_BALANCE": 0,
		"PAYMENT_METHOD_TYPE_CREDIT_CARD":     1,
		"PAYMENT_METHOD_TYPE_DEBIT_CARD":      2,
		"PAYMENT_METHOD_TYPE_PAYPAL":          3,
		"PAYMENT_METHOD_TYPE_APPLE_PAY":       4,
		"PAYMENT_METHOD_TYPE_GOOGLE_PAY":      5,
		"PAYMENT_METHOD_TYPE_BITCOIN":         6,
		"PAYMENT_METHOD_TYPE_ETHEREUM":        7,
		"PAYMENT_METHOD_TYPE_USDC":            8,
		"PAYMENT_METHOD_TYPE_BANK_TRANSFER":   9,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Account Type Enum
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_PERSONAL   AccountType = 0
	AccountType_ACCOUNT_TYPE_SAVINGS    AccountType = 1
	AccountType_ACCOUNT_TYPE_INVESTMENT AccountType = 2
	AccountType_ACCOUNT_TYPE_BUSINESS   AccountType = 3
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_PERSONAL",
		1: "ACCOUNT_TYPE_SAVINGS",
		2: "ACCOUNT_TYPE_INVESTMENT",
		3: "ACCOUNT_TYPE_BUSINESS",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_PERSONAL":   0,
		"ACCOUNT_TYPE_SAVINGS":    1,
		"ACCOUNT_TYPE_INVESTMENT": 2,
		"ACCOUNT_TYPE_BUSINESS":   3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Dispute Status Enum
type DisputeStatus int32

const (
	DisputeStatus_DISPUTE_STATUS_PENDING       DisputeStatus = 0
	DisputeStatus_DISPUTE_STATUS_INVESTIGATING DisputeStatus = 1
	DisputeStatus_DISPUTE_STATUS_RESOLVED      DisputeStatus = 2
	DisputeStatus_DISPUTE_STATUS_REJECTED      DisputeStatus = 3
	DisputeStatus_DISPUTE_STATUS_ESCALATED     DisputeStatus = 4
)

// Enum value maps for DisputeStatus.
var (
	DisputeStatus_name = map[int32]string{
		0: "DISPUTE_STATUS_PENDING",
		1: "DISPUTE_STATUS_INVESTIGATING",
		2: "DISPUTE_STATUS_RESOLVED",
		3: "DISPUTE_STATUS_REJECTED",
		4: "DISPUTE_STATUS_ESCALATED",
	}
	DisputeStatus_value = map[string]int32{
		"DISPUTE_STATUS_PENDING":       0,
		"DISPUTE_STATUS_INVESTIGATING": 1,
		"DISPUTE_STATUS_RESOLVED":      2,
		"DISPUTE_STATUS_REJECTED":      3,
		"DISPUTE_STATUS_ESCALATED":     4,
	}
)

func (x DisputeStatus) Enum() *DisputeStatus {
	p := new(DisputeStatus)
	*p = x
	return p
}

func (x DisputeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisputeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (DisputeStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x DisputeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisputeStatus.Descriptor instead.
func (DisputeStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// Invoice Priority Enum
type InvoicePriority int32

const (
	InvoicePriority_INVOICE_PRIORITY_LOW    InvoicePriority = 0
	InvoicePriority_INVOICE_PRIORITY_MEDIUM InvoicePriority = 1
	InvoicePriority_INVOICE_PRIORITY_HIGH   InvoicePriority = 2
	InvoicePriority_INVOICE_PRIORITY_URGENT InvoicePriority = 3
)

// Enum value maps for InvoicePriority.
var (
	InvoicePriority_name = map[int32]string{
		0: "INVOICE_PRIORITY_LOW",
		1: "INVOICE_PRIORITY_MEDIUM",
		2: "INVOICE_PRIORITY_HIGH",
		3: "INVOICE_PRIORITY_URGENT",
	}
	InvoicePriority_value = map[string]int32{
		"INVOICE_PRIORITY_LOW":    0,
		"INVOICE_PRIORITY_MEDIUM": 1,
		"INVOICE_PRIORITY_HIGH":   2,
		"INVOICE_PRIORITY_URGENT": 3,
	}
)

func (x InvoicePriority) Enum() *InvoicePriority {
	p := new(InvoicePriority)
	*p = x
	return p
}

func (x InvoicePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoicePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (InvoicePriority) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x InvoicePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoicePriority.Descriptor instead.
func (InvoicePriority) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// Common user type (for gateway-internal use, distinct from auth.proto User)
type CommonUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Username        string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Role            string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Verified        bool                   `protobuf:"varint,8,opt,name=verified,proto3" json:"verified,omitempty"`
	IsEmailVerified bool                   `protobuf:"varint,9,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Language        string                 `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	Currency        string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	Country         string                 `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	ProfilePicture  string                 `protobuf:"bytes,15,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	Roles           []string               `protobuf:"bytes,16,rep,name=roles,proto3" json:"roles,omitempty"`
	// The REAL user id. `id` above is a uint64 dating from numeric user ids,
	// but this platform's user ids are UUIDs, so every ParseUint on the way out
	// fails and `id` is silently 0 for EVERY user — the client's profile model
	// does `id.toString()` and gets "0". Changing field 1's type would break
	// the wire format for installed clients (varint vs length-delimited), so
	// the real value is carried here and `id` is left as the dead field it
	// already was.
	UserId        string `protobuf:"bytes,17,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonUser) Reset() {
	*x = CommonUser{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonUser) ProtoMessage() {}

func (x *CommonUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonUser.ProtoReflect.Descriptor instead.
func (*CommonUser) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CommonUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CommonUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CommonUser) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CommonUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommonUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CommonUser) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *CommonUser) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *CommonUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommonUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CommonUser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CommonUser) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CommonUser) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CommonUser) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *CommonUser) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CommonUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *CommonUser            `protobuf:"bytes,1,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Session       *CommonSession         `protobuf:"bytes,2,opt,name=session,proto3,oneof" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetUser() *CommonUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Data) GetSession() *CommonSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type CommonSession struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken           string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CommonSession) Reset() {
	*x = CommonSession{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSession) ProtoMessage() {}

func (x *CommonSession) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSession.ProtoReflect.Descriptor instead.
func (*CommonSession) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *CommonSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommonSession) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommonSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CommonSession) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CommonSession) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *CommonSession) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

// Pagination Info - Common pagination structure for gateway
type GatewayPaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	ItemsPerPage  int32                  `protobuf:"varint,4,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayPaginationInfo) Reset() {
	*x = GatewayPaginationInfo{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPaginationInfo) ProtoMessage() {}

func (x *GatewayPaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPaginationInfo.ProtoReflect.Descriptor instead.
func (*GatewayPaginationInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayPaginationInfo) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GatewayPaginationInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GatewayPaginationInfo) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GatewayPaginationInfo) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

func (x *GatewayPaginationInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *GatewayPaginationInfo) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x04\n" +
	"\n" +
	"CommonUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1a\n" +
	"\bverified\x18\b \x01(\bR\bverified\x12*\n" +
	"\x11is_email_verified\x18\t \x01(\bR\x0fisEmailVerified\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12\x18\n" +
	"\acountry\x18\x0e \x01(\tR\acountry\x12'\n" +
	"\x0fprofile_picture\x18\x0f \x01(\tR\x0eprofilePicture\x12\x14\n" +
	"\x05roles\x18\x10 \x03(\tR\x05roles\x12\x17\n" +
	"\auser_id\x18\x11 \x01(\tR\x06userId\"v\n" +
	"\x04Data\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.pb.CommonUserH\x00R\x04user\x88\x01\x01\x120\n" +
	"\asession\x18\x02 \x01(\v2\x11.pb.CommonSessionH\x01R\asession\x88\x01\x01B\a\n" +
	"\x05_userB\n" +
	"\n" +
	"\b_session\"\xa8\x02\n" +
	"\rCommonSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAt\"\xd8\x01\n" +
	"\x15GatewayPaginationInfo\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12$\n" +
	"\x0eitems_per_page\x18\x04 \x01(\x05R\fitemsPerPage\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x06 \x01(\bR\ahasPrev*\xe9\x02\n" +
	"\x14InvoicePaymentStatus\x12\"\n" +
	"\x1eINVOICE_PAYMENT_STATUS_PENDING\x10\x00\x12%\n" +
	"!INVOICE_PAYMENT_STATUS_PROCESSING\x10\x01\x12$\n" +
	" INVOICE_PAYMENT_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dINVOICE_PAYMENT_STATUS_FAILED\x10\x03\x12$\n" +
	" INVOICE_PAYMENT_STATUS_CANCELLED\x10\x04\x12)\n" +
	"%INVOICE_PAYMENT_STATUS_PARTIALLY_PAID\x10\x05\x12#\n" +
	"\x1fINVOICE_PAYMENT_STATUS_REFUNDED\x10\x06\x12#\n" +
	"\x1fINVOICE_PAYMENT_STATUS_DISPUTED\x10\a\x12\"\n" +
	"\x1eINVOICE_PAYMENT_STATUS_OVERDUE\x10\b*\xf4\x02\n" +
	"\x11PaymentMethodType\x12'\n" +
	"#PAYMENT_METHOD_TYPE_ACCOUNT_BALANCE\x10\x00\x12#\n" +
	"\x1fPAYMENT_METHOD_TYPE_CREDIT_CARD\x10\x01\x12\"\n" +
	"\x1ePAYMENT_METHOD_TYPE_DEBIT_CARD\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_TYPE_PAYPAL\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_TYPE_APPLE_PAY\x10\x04\x12\"\n" +
	"\x1ePAYMENT_METHOD_TYPE_GOOGLE_PAY\x10\x05\x12\x1f\n" +
	"\x1bPAYMENT_METHOD_TYPE_BITCOIN\x10\x06\x12 \n" +
	"\x1cPAYMENT_METHOD_TYPE_ETHEREUM\x10\a\x12\x1c\n" +
	"\x18PAYMENT_METHOD_TYPE_USDC\x10\b\x12%\n" +
	"!PAYMENT_METHOD_TYPE_BANK_TRANSFER\x10\t*z\n" +
	"\vAccountType\x12\x19\n" +
	"\x15ACCOUNT_TYPE_PERSONAL\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_TYPE_BUSINESS\x10\x03*\xa5\x01\n" +
	"\rDisputeStatus\x12\x1a\n" +
	"\x16DISPUTE_STATUS_PENDING\x10\x00\x12 \n" +
	"\x1cDISPUTE_STATUS_INVESTIGATING\x10\x01\x12\x1b\n" +
	"\x17DISPUTE_STATUS_RESOLVED\x10\x02\x12\x1b\n" +
	"\x17DISPUTE_STATUS_REJECTED\x10\x03\x12\x1c\n" +
	"\x18DISPUTE_STATUS_ESCALATED\x10\x04*\x80\x01\n" +
	"\x0fInvoicePriority\x12\x18\n" +
	"\x14INVOICE_PRIORITY_LOW\x10\x00\x12\x1b\n" +
	"\x17INVOICE_PRIORITY_MEDIUM\x10\x01\x12\x19\n" +
	"\x15INVOICE_PRIORITY_HIGH\x10\x02\x12\x1b\n" +
	"\x17INVOICE_PRIORITY_URGENT\x10\x03B\x11Z\x0flazervaultGo/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(InvoicePaymentStatus)(0),     // 0: pb.InvoicePaymentStatus
	(PaymentMethodType)(0),        // 1: pb.PaymentMethodType
	(AccountType)(0),              // 2: pb.AccountType
	(DisputeStatus)(0),            // 3: pb.DisputeStatus
	(InvoicePriority)(0),          // 4: pb.InvoicePriority
	(*CommonUser)(nil),            // 5: pb.CommonUser
	(*Data)(nil),                  // 6: pb.Data
	(*CommonSession)(nil),         // 7: pb.CommonSession
	(*GatewayPaginationInfo)(nil), // 8: pb.GatewayPaginationInfo
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	9, // 0: pb.CommonUser.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: pb.CommonUser.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: pb.Data.user:type_name -> pb.CommonUser
	7, // 3: pb.Data.session:type_name -> pb.CommonSession
	9, // 4: pb.CommonSession.access_token_expires_at:type_name -> google.protobuf.Timestamp
	9, // 5: pb.CommonSession.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
