// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: account_card.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountCardService_AddAccountCard_FullMethodName                 = "/pb.AccountCardService/AddAccountCard"
	AccountCardService_GetAccountCards_FullMethodName                = "/pb.AccountCardService/GetAccountCards"
	AccountCardService_UpdateAccountCardDefaultStatus_FullMethodName = "/pb.AccountCardService/UpdateAccountCardDefaultStatus"
	AccountCardService_DeleteAccountCard_FullMethodName              = "/pb.AccountCardService/DeleteAccountCard"
)

// AccountCardServiceClient is the client API for AccountCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountCardServiceClient interface {
	// Adds a new card to a specific account owned by the authenticated user
	AddAccountCard(ctx context.Context, in *AddAccountCardRequest, opts ...grpc.CallOption) (*AddAccountCardResponse, error)
	// Gets all cards linked to a specific account owned by the authenticated user
	GetAccountCards(ctx context.Context, in *GetAccountCardsRequest, opts ...grpc.CallOption) (*GetAccountCardsResponse, error)
	// Sets a specific card as the default for an account
	UpdateAccountCardDefaultStatus(ctx context.Context, in *UpdateAccountCardDefaultStatusRequest, opts ...grpc.CallOption) (*UpdateAccountCardDefaultStatusResponse, error)
	// Deletes a specific card from an account
	DeleteAccountCard(ctx context.Context, in *DeleteAccountCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type accountCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountCardServiceClient(cc grpc.ClientConnInterface) AccountCardServiceClient {
	return &accountCardServiceClient{cc}
}

func (c *accountCardServiceClient) AddAccountCard(ctx context.Context, in *AddAccountCardRequest, opts ...grpc.CallOption) (*AddAccountCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAccountCardResponse)
	err := c.cc.Invoke(ctx, AccountCardService_AddAccountCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) GetAccountCards(ctx context.Context, in *GetAccountCardsRequest, opts ...grpc.CallOption) (*GetAccountCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountCardsResponse)
	err := c.cc.Invoke(ctx, AccountCardService_GetAccountCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) UpdateAccountCardDefaultStatus(ctx context.Context, in *UpdateAccountCardDefaultStatusRequest, opts ...grpc.CallOption) (*UpdateAccountCardDefaultStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccountCardDefaultStatusResponse)
	err := c.cc.Invoke(ctx, AccountCardService_UpdateAccountCardDefaultStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCardServiceClient) DeleteAccountCard(ctx context.Context, in *DeleteAccountCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountCardService_DeleteAccountCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCardServiceServer is the server API for AccountCardService service.
// All implementations must embed UnimplementedAccountCardServiceServer
// for forward compatibility.
type AccountCardServiceServer interface {
	// Adds a new card to a specific account owned by the authenticated user
	AddAccountCard(context.Context, *AddAccountCardRequest) (*AddAccountCardResponse, error)
	// Gets all cards linked to a specific account owned by the authenticated user
	GetAccountCards(context.Context, *GetAccountCardsRequest) (*GetAccountCardsResponse, error)
	// Sets a specific card as the default for an account
	UpdateAccountCardDefaultStatus(context.Context, *UpdateAccountCardDefaultStatusRequest) (*UpdateAccountCardDefaultStatusResponse, error)
	// Deletes a specific card from an account
	DeleteAccountCard(context.Context, *DeleteAccountCardRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAccountCardServiceServer()
}

// UnimplementedAccountCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountCardServiceServer struct{}

func (UnimplementedAccountCardServiceServer) AddAccountCard(context.Context, *AddAccountCardRequest) (*AddAccountCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountCard not implemented")
}
func (UnimplementedAccountCardServiceServer) GetAccountCards(context.Context, *GetAccountCardsRequest) (*GetAccountCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountCards not implemented")
}
func (UnimplementedAccountCardServiceServer) UpdateAccountCardDefaultStatus(context.Context, *UpdateAccountCardDefaultStatusRequest) (*UpdateAccountCardDefaultStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountCardDefaultStatus not implemented")
}
func (UnimplementedAccountCardServiceServer) DeleteAccountCard(context.Context, *DeleteAccountCardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountCard not implemented")
}
func (UnimplementedAccountCardServiceServer) mustEmbedUnimplementedAccountCardServiceServer() {}
func (UnimplementedAccountCardServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountCardServiceServer will
// result in compilation errors.
type UnsafeAccountCardServiceServer interface {
	mustEmbedUnimplementedAccountCardServiceServer()
}

func RegisterAccountCardServiceServer(s grpc.ServiceRegistrar, srv AccountCardServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountCardService_ServiceDesc, srv)
}

func _AccountCardService_AddAccountCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).AddAccountCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_AddAccountCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).AddAccountCard(ctx, req.(*AddAccountCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_GetAccountCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).GetAccountCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_GetAccountCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).GetAccountCards(ctx, req.(*GetAccountCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_UpdateAccountCardDefaultStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountCardDefaultStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).UpdateAccountCardDefaultStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_UpdateAccountCardDefaultStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).UpdateAccountCardDefaultStatus(ctx, req.(*UpdateAccountCardDefaultStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCardService_DeleteAccountCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCardServiceServer).DeleteAccountCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCardService_DeleteAccountCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCardServiceServer).DeleteAccountCard(ctx, req.(*DeleteAccountCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountCardService_ServiceDesc is the grpc.ServiceDesc for AccountCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AccountCardService",
	HandlerType: (*AccountCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAccountCard",
			Handler:    _AccountCardService_AddAccountCard_Handler,
		},
		{
			MethodName: "GetAccountCards",
			Handler:    _AccountCardService_GetAccountCards_Handler,
		},
		{
			MethodName: "UpdateAccountCardDefaultStatus",
			Handler:    _AccountCardService_UpdateAccountCardDefaultStatus_Handler,
		},
		{
			MethodName: "DeleteAccountCard",
			Handler:    _AccountCardService_DeleteAccountCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_card.proto",
}
