// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: ai_scan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiScanService_StartScanSession_FullMethodName           = "/ai_scan.AiScanService/StartScanSession"
	AiScanService_ProcessImage_FullMethodName               = "/ai_scan.AiScanService/ProcessImage"
	AiScanService_SendChatMessage_FullMethodName            = "/ai_scan.AiScanService/SendChatMessage"
	AiScanService_GeneratePaymentInstruction_FullMethodName = "/ai_scan.AiScanService/GeneratePaymentInstruction"
	AiScanService_ProcessPayment_FullMethodName             = "/ai_scan.AiScanService/ProcessPayment"
	AiScanService_GetScanHistory_FullMethodName             = "/ai_scan.AiScanService/GetScanHistory"
)

// AiScanServiceClient is the client API for AiScanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI Scan Service for extracting data from images
type AiScanServiceClient interface {
	// Start a new scan session
	StartScanSession(ctx context.Context, in *StartScanSessionRequest, opts ...grpc.CallOption) (*StartScanSessionResponse, error)
	// Process an image and extract data
	ProcessImage(ctx context.Context, in *ProcessImageRequest, opts ...grpc.CallOption) (*ProcessImageResponse, error)
	// Send a chat message and get AI response
	SendChatMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error)
	// Generate payment instruction from extracted data
	GeneratePaymentInstruction(ctx context.Context, in *GeneratePaymentInstructionRequest, opts ...grpc.CallOption) (*GeneratePaymentInstructionResponse, error)
	// Process the generated payment
	ProcessPayment(ctx context.Context, in *ScanProcessPaymentRequest, opts ...grpc.CallOption) (*ScanProcessPaymentResponse, error)
	// Get scan history for a user
	GetScanHistory(ctx context.Context, in *GetScanHistoryRequest, opts ...grpc.CallOption) (*GetScanHistoryResponse, error)
}

type aiScanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiScanServiceClient(cc grpc.ClientConnInterface) AiScanServiceClient {
	return &aiScanServiceClient{cc}
}

func (c *aiScanServiceClient) StartScanSession(ctx context.Context, in *StartScanSessionRequest, opts ...grpc.CallOption) (*StartScanSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartScanSessionResponse)
	err := c.cc.Invoke(ctx, AiScanService_StartScanSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiScanServiceClient) ProcessImage(ctx context.Context, in *ProcessImageRequest, opts ...grpc.CallOption) (*ProcessImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessImageResponse)
	err := c.cc.Invoke(ctx, AiScanService_ProcessImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiScanServiceClient) SendChatMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatMessageResponse)
	err := c.cc.Invoke(ctx, AiScanService_SendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiScanServiceClient) GeneratePaymentInstruction(ctx context.Context, in *GeneratePaymentInstructionRequest, opts ...grpc.CallOption) (*GeneratePaymentInstructionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePaymentInstructionResponse)
	err := c.cc.Invoke(ctx, AiScanService_GeneratePaymentInstruction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiScanServiceClient) ProcessPayment(ctx context.Context, in *ScanProcessPaymentRequest, opts ...grpc.CallOption) (*ScanProcessPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanProcessPaymentResponse)
	err := c.cc.Invoke(ctx, AiScanService_ProcessPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiScanServiceClient) GetScanHistory(ctx context.Context, in *GetScanHistoryRequest, opts ...grpc.CallOption) (*GetScanHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScanHistoryResponse)
	err := c.cc.Invoke(ctx, AiScanService_GetScanHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiScanServiceServer is the server API for AiScanService service.
// All implementations must embed UnimplementedAiScanServiceServer
// for forward compatibility.
//
// AI Scan Service for extracting data from images
type AiScanServiceServer interface {
	// Start a new scan session
	StartScanSession(context.Context, *StartScanSessionRequest) (*StartScanSessionResponse, error)
	// Process an image and extract data
	ProcessImage(context.Context, *ProcessImageRequest) (*ProcessImageResponse, error)
	// Send a chat message and get AI response
	SendChatMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error)
	// Generate payment instruction from extracted data
	GeneratePaymentInstruction(context.Context, *GeneratePaymentInstructionRequest) (*GeneratePaymentInstructionResponse, error)
	// Process the generated payment
	ProcessPayment(context.Context, *ScanProcessPaymentRequest) (*ScanProcessPaymentResponse, error)
	// Get scan history for a user
	GetScanHistory(context.Context, *GetScanHistoryRequest) (*GetScanHistoryResponse, error)
	mustEmbedUnimplementedAiScanServiceServer()
}

// UnimplementedAiScanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiScanServiceServer struct{}

func (UnimplementedAiScanServiceServer) StartScanSession(context.Context, *StartScanSessionRequest) (*StartScanSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartScanSession not implemented")
}
func (UnimplementedAiScanServiceServer) ProcessImage(context.Context, *ProcessImageRequest) (*ProcessImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessImage not implemented")
}
func (UnimplementedAiScanServiceServer) SendChatMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedAiScanServiceServer) GeneratePaymentInstruction(context.Context, *GeneratePaymentInstructionRequest) (*GeneratePaymentInstructionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePaymentInstruction not implemented")
}
func (UnimplementedAiScanServiceServer) ProcessPayment(context.Context, *ScanProcessPaymentRequest) (*ScanProcessPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedAiScanServiceServer) GetScanHistory(context.Context, *GetScanHistoryRequest) (*GetScanHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScanHistory not implemented")
}
func (UnimplementedAiScanServiceServer) mustEmbedUnimplementedAiScanServiceServer() {}
func (UnimplementedAiScanServiceServer) testEmbeddedByValue()                       {}

// UnsafeAiScanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiScanServiceServer will
// result in compilation errors.
type UnsafeAiScanServiceServer interface {
	mustEmbedUnimplementedAiScanServiceServer()
}

func RegisterAiScanServiceServer(s grpc.ServiceRegistrar, srv AiScanServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiScanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiScanService_ServiceDesc, srv)
}

func _AiScanService_StartScanSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScanSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).StartScanSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_StartScanSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).StartScanSession(ctx, req.(*StartScanSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiScanService_ProcessImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).ProcessImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_ProcessImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).ProcessImage(ctx, req.(*ProcessImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiScanService_SendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).SendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_SendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).SendChatMessage(ctx, req.(*SendChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiScanService_GeneratePaymentInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePaymentInstructionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).GeneratePaymentInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_GeneratePaymentInstruction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).GeneratePaymentInstruction(ctx, req.(*GeneratePaymentInstructionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiScanService_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanProcessPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_ProcessPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).ProcessPayment(ctx, req.(*ScanProcessPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiScanService_GetScanHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScanHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiScanServiceServer).GetScanHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiScanService_GetScanHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiScanServiceServer).GetScanHistory(ctx, req.(*GetScanHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiScanService_ServiceDesc is the grpc.ServiceDesc for AiScanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiScanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_scan.AiScanService",
	HandlerType: (*AiScanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScanSession",
			Handler:    _AiScanService_StartScanSession_Handler,
		},
		{
			MethodName: "ProcessImage",
			Handler:    _AiScanService_ProcessImage_Handler,
		},
		{
			MethodName: "SendChatMessage",
			Handler:    _AiScanService_SendChatMessage_Handler,
		},
		{
			MethodName: "GeneratePaymentInstruction",
			Handler:    _AiScanService_GeneratePaymentInstruction_Handler,
		},
		{
			MethodName: "ProcessPayment",
			Handler:    _AiScanService_ProcessPayment_Handler,
		},
		{
			MethodName: "GetScanHistory",
			Handler:    _AiScanService_GetScanHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_scan.proto",
}
