// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: portfolio.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortfolioAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetType       string                 `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"` // "crypto", "stock", "investment", "account", "savings", "financial_goal"
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol          string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CurrentValue    float64                `protobuf:"fixed64,5,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Quantity        float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CurrentPrice    float64                `protobuf:"fixed64,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	InitialValue    float64                `protobuf:"fixed64,8,opt,name=initial_value,json=initialValue,proto3" json:"initial_value,omitempty"`
	GainLoss        float64                `protobuf:"fixed64,9,opt,name=gain_loss,json=gainLoss,proto3" json:"gain_loss,omitempty"`
	GainLossPercent float64                `protobuf:"fixed64,10,opt,name=gain_loss_percent,json=gainLossPercent,proto3" json:"gain_loss_percent,omitempty"`
	Currency        string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	LastUpdated     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	IconUrl         string                 `protobuf:"bytes,13,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PortfolioAsset) Reset() {
	*x = PortfolioAsset{}
	mi := &file_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioAsset) ProtoMessage() {}

func (x *PortfolioAsset) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioAsset.ProtoReflect.Descriptor instead.
func (*PortfolioAsset) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortfolioAsset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *PortfolioAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortfolioAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PortfolioAsset) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *PortfolioAsset) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PortfolioAsset) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *PortfolioAsset) GetInitialValue() float64 {
	if x != nil {
		return x.InitialValue
	}
	return 0
}

func (x *PortfolioAsset) GetGainLoss() float64 {
	if x != nil {
		return x.GainLoss
	}
	return 0
}

func (x *PortfolioAsset) GetGainLossPercent() float64 {
	if x != nil {
		return x.GainLossPercent
	}
	return 0
}

func (x *PortfolioAsset) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PortfolioAsset) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *PortfolioAsset) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type PortfolioSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalValue           float64                `protobuf:"fixed64,1,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalGainLoss        float64                `protobuf:"fixed64,2,opt,name=total_gain_loss,json=totalGainLoss,proto3" json:"total_gain_loss,omitempty"`
	TotalGainLossPercent float64                `protobuf:"fixed64,3,opt,name=total_gain_loss_percent,json=totalGainLossPercent,proto3" json:"total_gain_loss_percent,omitempty"`
	TotalInvested        float64                `protobuf:"fixed64,4,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	Currency             string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	AssetsByType         map[string]float64     `protobuf:"bytes,6,rep,name=assets_by_type,json=assetsByType,proto3" json:"assets_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	AssetCount           int32                  `protobuf:"varint,7,opt,name=asset_count,json=assetCount,proto3" json:"asset_count,omitempty"`
	LastUpdated          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PortfolioSummary) Reset() {
	*x = PortfolioSummary{}
	mi := &file_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioSummary) ProtoMessage() {}

func (x *PortfolioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioSummary.ProtoReflect.Descriptor instead.
func (*PortfolioSummary) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioSummary) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioSummary) GetTotalGainLoss() float64 {
	if x != nil {
		return x.TotalGainLoss
	}
	return 0
}

func (x *PortfolioSummary) GetTotalGainLossPercent() float64 {
	if x != nil {
		return x.TotalGainLossPercent
	}
	return 0
}

func (x *PortfolioSummary) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *PortfolioSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PortfolioSummary) GetAssetsByType() map[string]float64 {
	if x != nil {
		return x.AssetsByType
	}
	return nil
}

func (x *PortfolioSummary) GetAssetCount() int32 {
	if x != nil {
		return x.AssetCount
	}
	return 0
}

func (x *PortfolioSummary) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Get Complete Portfolio Request/Response
type GetCompletePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletePortfolioRequest) Reset() {
	*x = GetCompletePortfolioRequest{}
	mi := &file_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletePortfolioRequest) ProtoMessage() {}

func (x *GetCompletePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletePortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetCompletePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{2}
}

type GetCompletePortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Summary       *PortfolioSummary      `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Assets        []*PortfolioAsset      `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletePortfolioResponse) Reset() {
	*x = GetCompletePortfolioResponse{}
	mi := &file_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletePortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletePortfolioResponse) ProtoMessage() {}

func (x *GetCompletePortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletePortfolioResponse.ProtoReflect.Descriptor instead.
func (*GetCompletePortfolioResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *GetCompletePortfolioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCompletePortfolioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCompletePortfolioResponse) GetSummary() *PortfolioSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetCompletePortfolioResponse) GetAssets() []*PortfolioAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

// Get Portfolio By Asset Type Request/Response
type GetPortfolioByAssetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetType     string                 `protobuf:"bytes,1,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"` // "crypto", "stock", "investment", "account", "savings"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioByAssetTypeRequest) Reset() {
	*x = GetPortfolioByAssetTypeRequest{}
	mi := &file_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioByAssetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioByAssetTypeRequest) ProtoMessage() {}

func (x *GetPortfolioByAssetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioByAssetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioByAssetTypeRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *GetPortfolioByAssetTypeRequest) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

type GetPortfolioByAssetTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Assets        []*PortfolioAsset      `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioByAssetTypeResponse) Reset() {
	*x = GetPortfolioByAssetTypeResponse{}
	mi := &file_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioByAssetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioByAssetTypeResponse) ProtoMessage() {}

func (x *GetPortfolioByAssetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioByAssetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioByAssetTypeResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *GetPortfolioByAssetTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPortfolioByAssetTypeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPortfolioByAssetTypeResponse) GetAssets() []*PortfolioAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetPortfolioByAssetTypeResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// Get Portfolio History Request/Response
type GetPortfolioHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // "1D", "1W", "1M", "3M", "1Y", "ALL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioHistoryRequest) Reset() {
	*x = GetPortfolioHistoryRequest{}
	mi := &file_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioHistoryRequest) ProtoMessage() {}

func (x *GetPortfolioHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioHistoryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *GetPortfolioHistoryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type PortfolioHistoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioHistoryPoint) Reset() {
	*x = PortfolioHistoryPoint{}
	mi := &file_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioHistoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioHistoryPoint) ProtoMessage() {}

func (x *PortfolioHistoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioHistoryPoint.ProtoReflect.Descriptor instead.
func (*PortfolioHistoryPoint) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *PortfolioHistoryPoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *PortfolioHistoryPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetPortfolioHistoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Success       bool                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []*PortfolioHistoryPoint `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioHistoryResponse) Reset() {
	*x = GetPortfolioHistoryResponse{}
	mi := &file_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioHistoryResponse) ProtoMessage() {}

func (x *GetPortfolioHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioHistoryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *GetPortfolioHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPortfolioHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPortfolioHistoryResponse) GetHistory() []*PortfolioHistoryPoint {
	if x != nil {
		return x.History
	}
	return nil
}

// Get Portfolio Summary Request/Response
type GetPortfolioSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryRequest) Reset() {
	*x = GetPortfolioSummaryRequest{}
	mi := &file_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryRequest) ProtoMessage() {}

func (x *GetPortfolioSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{9}
}

type GetPortfolioSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Summary       *PortfolioSummary      `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryResponse) Reset() {
	*x = GetPortfolioSummaryResponse{}
	mi := &file_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryResponse) ProtoMessage() {}

func (x *GetPortfolioSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *GetPortfolioSummaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPortfolioSummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPortfolioSummaryResponse) GetSummary() *PortfolioSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x0fportfolio.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xb5\x03\n" +
	"\x0ePortfolioAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\tR\tassetType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12#\n" +
	"\rcurrent_value\x18\x05 \x01(\x01R\fcurrentValue\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12#\n" +
	"\rcurrent_price\x18\a \x01(\x01R\fcurrentPrice\x12#\n" +
	"\rinitial_value\x18\b \x01(\x01R\finitialValue\x12\x1b\n" +
	"\tgain_loss\x18\t \x01(\x01R\bgainLoss\x12*\n" +
	"\x11gain_loss_percent\x18\n" +
	" \x01(\x01R\x0fgainLossPercent\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12=\n" +
	"\flast_updated\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x19\n" +
	"\bicon_url\x18\r \x01(\tR\aiconUrl\"\xc4\x03\n" +
	"\x10PortfolioSummary\x12\x1f\n" +
	"\vtotal_value\x18\x01 \x01(\x01R\n" +
	"totalValue\x12&\n" +
	"\x0ftotal_gain_loss\x18\x02 \x01(\x01R\rtotalGainLoss\x125\n" +
	"\x17total_gain_loss_percent\x18\x03 \x01(\x01R\x14totalGainLossPercent\x12%\n" +
	"\x0etotal_invested\x18\x04 \x01(\x01R\rtotalInvested\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12L\n" +
	"\x0eassets_by_type\x18\x06 \x03(\v2&.pb.PortfolioSummary.AssetsByTypeEntryR\fassetsByType\x12\x1f\n" +
	"\vasset_count\x18\a \x01(\x05R\n" +
	"assetCount\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1a?\n" +
	"\x11AssetsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x1d\n" +
	"\x1bGetCompletePortfolioRequest\"\xae\x01\n" +
	"\x1cGetCompletePortfolioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\asummary\x18\x03 \x01(\v2\x14.pb.PortfolioSummaryR\asummary\x12*\n" +
	"\x06assets\x18\x04 \x03(\v2\x12.pb.PortfolioAssetR\x06assets\"?\n" +
	"\x1eGetPortfolioByAssetTypeRequest\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x01 \x01(\tR\tassetType\"\xa2\x01\n" +
	"\x1fGetPortfolioByAssetTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06assets\x18\x03 \x03(\v2\x12.pb.PortfolioAssetR\x06assets\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x01R\n" +
	"totalValue\"4\n" +
	"\x1aGetPortfolioHistoryRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"]\n" +
	"\x15PortfolioHistoryPoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x86\x01\n" +
	"\x1bGetPortfolioHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\ahistory\x18\x03 \x03(\v2\x19.pb.PortfolioHistoryPointR\ahistory\"\x1c\n" +
	"\x1aGetPortfolioSummaryRequest\"\x81\x01\n" +
	"\x1bGetPortfolioSummaryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\asummary\x18\x03 \x01(\v2\x14.pb.PortfolioSummaryR\asummary2\x8b\x04\n" +
	"\x10PortfolioService\x12|\n" +
	"\x14GetCompletePortfolio\x12\x1f.pb.GetCompletePortfolioRequest\x1a .pb.GetCompletePortfolioResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/portfolio/complete\x12\x84\x01\n" +
	"\x17GetPortfolioByAssetType\x12\".pb.GetPortfolioByAssetTypeRequest\x1a#.pb.GetPortfolioByAssetTypeResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/portfolio/by-type\x12x\n" +
	"\x13GetPortfolioHistory\x12\x1e.pb.GetPortfolioHistoryRequest\x1a\x1f.pb.GetPortfolioHistoryResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/portfolio/history\x12x\n" +
	"\x13GetPortfolioSummary\x12\x1e.pb.GetPortfolioSummaryRequest\x1a\x1f.pb.GetPortfolioSummaryResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/portfolio/summaryB\x11Z\x0flazervaultGo/pbb\x06proto3"

var (
	file_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_proto_rawDescData []byte
)

func file_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)))
	})
	return file_portfolio_proto_rawDescData
}

var file_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_portfolio_proto_goTypes = []any{
	(*PortfolioAsset)(nil),                  // 0: pb.PortfolioAsset
	(*PortfolioSummary)(nil),                // 1: pb.PortfolioSummary
	(*GetCompletePortfolioRequest)(nil),     // 2: pb.GetCompletePortfolioRequest
	(*GetCompletePortfolioResponse)(nil),    // 3: pb.GetCompletePortfolioResponse
	(*GetPortfolioByAssetTypeRequest)(nil),  // 4: pb.GetPortfolioByAssetTypeRequest
	(*GetPortfolioByAssetTypeResponse)(nil), // 5: pb.GetPortfolioByAssetTypeResponse
	(*GetPortfolioHistoryRequest)(nil),      // 6: pb.GetPortfolioHistoryRequest
	(*PortfolioHistoryPoint)(nil),           // 7: pb.PortfolioHistoryPoint
	(*GetPortfolioHistoryResponse)(nil),     // 8: pb.GetPortfolioHistoryResponse
	(*GetPortfolioSummaryRequest)(nil),      // 9: pb.GetPortfolioSummaryRequest
	(*GetPortfolioSummaryResponse)(nil),     // 10: pb.GetPortfolioSummaryResponse
	nil,                                     // 11: pb.PortfolioSummary.AssetsByTypeEntry
	(*timestamppb.Timestamp)(nil),           // 12: google.protobuf.Timestamp
}
var file_portfolio_proto_depIdxs = []int32{
	12, // 0: pb.PortfolioAsset.last_updated:type_name -> google.protobuf.Timestamp
	11, // 1: pb.PortfolioSummary.assets_by_type:type_name -> pb.PortfolioSummary.AssetsByTypeEntry
	12, // 2: pb.PortfolioSummary.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 3: pb.GetCompletePortfolioResponse.summary:type_name -> pb.PortfolioSummary
	0,  // 4: pb.GetCompletePortfolioResponse.assets:type_name -> pb.PortfolioAsset
	0,  // 5: pb.GetPortfolioByAssetTypeResponse.assets:type_name -> pb.PortfolioAsset
	12, // 6: pb.PortfolioHistoryPoint.date:type_name -> google.protobuf.Timestamp
	7,  // 7: pb.GetPortfolioHistoryResponse.history:type_name -> pb.PortfolioHistoryPoint
	1,  // 8: pb.GetPortfolioSummaryResponse.summary:type_name -> pb.PortfolioSummary
	2,  // 9: pb.PortfolioService.GetCompletePortfolio:input_type -> pb.GetCompletePortfolioRequest
	4,  // 10: pb.PortfolioService.GetPortfolioByAssetType:input_type -> pb.GetPortfolioByAssetTypeRequest
	6,  // 11: pb.PortfolioService.GetPortfolioHistory:input_type -> pb.GetPortfolioHistoryRequest
	9,  // 12: pb.PortfolioService.GetPortfolioSummary:input_type -> pb.GetPortfolioSummaryRequest
	3,  // 13: pb.PortfolioService.GetCompletePortfolio:output_type -> pb.GetCompletePortfolioResponse
	5,  // 14: pb.PortfolioService.GetPortfolioByAssetType:output_type -> pb.GetPortfolioByAssetTypeResponse
	8,  // 15: pb.PortfolioService.GetPortfolioHistory:output_type -> pb.GetPortfolioHistoryResponse
	10, // 16: pb.PortfolioService.GetPortfolioSummary:output_type -> pb.GetPortfolioSummaryResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_portfolio_proto_init() }
func file_portfolio_proto_init() {
	if File_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_proto_depIdxs,
		MessageInfos:      file_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_proto = out.File
	file_portfolio_proto_goTypes = nil
	file_portfolio_proto_depIdxs = nil
}
