// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: referral.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Referral status enum
type ReferralStatus int32

const (
	ReferralStatus_REFERRAL_STATUS_PENDING   ReferralStatus = 0
	ReferralStatus_REFERRAL_STATUS_COMPLETED ReferralStatus = 1
	ReferralStatus_REFERRAL_STATUS_FAILED    ReferralStatus = 2
	ReferralStatus_REFERRAL_STATUS_CANCELLED ReferralStatus = 3
)

// Enum value maps for ReferralStatus.
var (
	ReferralStatus_name = map[int32]string{
		0: "REFERRAL_STATUS_PENDING",
		1: "REFERRAL_STATUS_COMPLETED",
		2: "REFERRAL_STATUS_FAILED",
		3: "REFERRAL_STATUS_CANCELLED",
	}
	ReferralStatus_value = map[string]int32{
		"REFERRAL_STATUS_PENDING":   0,
		"REFERRAL_STATUS_COMPLETED": 1,
		"REFERRAL_STATUS_FAILED":    2,
		"REFERRAL_STATUS_CANCELLED": 3,
	}
)

func (x ReferralStatus) Enum() *ReferralStatus {
	p := new(ReferralStatus)
	*p = x
	return p
}

func (x ReferralStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferralStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_referral_proto_enumTypes[0].Descriptor()
}

func (ReferralStatus) Type() protoreflect.EnumType {
	return &file_referral_proto_enumTypes[0]
}

func (x ReferralStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferralStatus.Descriptor instead.
func (ReferralStatus) EnumDescriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{0}
}

// ReferralCode message represents a user's referral code
type ReferralCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferralCode) Reset() {
	*x = ReferralCode{}
	mi := &file_referral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralCode) ProtoMessage() {}

func (x *ReferralCode) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralCode.ProtoReflect.Descriptor instead.
func (*ReferralCode) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{0}
}

func (x *ReferralCode) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReferralCode) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReferralCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReferralCode) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ReferralCode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReferralCode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ReferralTransaction message represents a referral event
type ReferralTransaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferrerUserId       uint64                 `protobuf:"varint,2,opt,name=referrer_user_id,json=referrerUserId,proto3" json:"referrer_user_id,omitempty"`
	RefereeUserId        uint64                 `protobuf:"varint,3,opt,name=referee_user_id,json=refereeUserId,proto3" json:"referee_user_id,omitempty"`
	ReferralCodeUsed     string                 `protobuf:"bytes,4,opt,name=referral_code_used,json=referralCodeUsed,proto3" json:"referral_code_used,omitempty"`
	Status               ReferralStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=pb.ReferralStatus" json:"status,omitempty"`
	ReferrerRewardAmount int32                  `protobuf:"varint,6,opt,name=referrer_reward_amount,json=referrerRewardAmount,proto3" json:"referrer_reward_amount,omitempty"`
	RefereeRewardAmount  int32                  `protobuf:"varint,7,opt,name=referee_reward_amount,json=refereeRewardAmount,proto3" json:"referee_reward_amount,omitempty"`
	Currency             string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	FailureReason        string                 `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReferralTransaction) Reset() {
	*x = ReferralTransaction{}
	mi := &file_referral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralTransaction) ProtoMessage() {}

func (x *ReferralTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralTransaction.ProtoReflect.Descriptor instead.
func (*ReferralTransaction) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{1}
}

func (x *ReferralTransaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReferralTransaction) GetReferrerUserId() uint64 {
	if x != nil {
		return x.ReferrerUserId
	}
	return 0
}

func (x *ReferralTransaction) GetRefereeUserId() uint64 {
	if x != nil {
		return x.RefereeUserId
	}
	return 0
}

func (x *ReferralTransaction) GetReferralCodeUsed() string {
	if x != nil {
		return x.ReferralCodeUsed
	}
	return ""
}

func (x *ReferralTransaction) GetStatus() ReferralStatus {
	if x != nil {
		return x.Status
	}
	return ReferralStatus_REFERRAL_STATUS_PENDING
}

func (x *ReferralTransaction) GetReferrerRewardAmount() int32 {
	if x != nil {
		return x.ReferrerRewardAmount
	}
	return 0
}

func (x *ReferralTransaction) GetRefereeRewardAmount() int32 {
	if x != nil {
		return x.RefereeRewardAmount
	}
	return 0
}

func (x *ReferralTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReferralTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReferralTransaction) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ReferralTransaction) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// CountryRewardConfig message represents country-specific reward configuration
type CountryRewardConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryCode    string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ReferrerReward int32                  `protobuf:"varint,4,opt,name=referrer_reward,json=referrerReward,proto3" json:"referrer_reward,omitempty"`
	RefereeReward  int32                  `protobuf:"varint,5,opt,name=referee_reward,json=refereeReward,proto3" json:"referee_reward,omitempty"`
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CountryRewardConfig) Reset() {
	*x = CountryRewardConfig{}
	mi := &file_referral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryRewardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryRewardConfig) ProtoMessage() {}

func (x *CountryRewardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryRewardConfig.ProtoReflect.Descriptor instead.
func (*CountryRewardConfig) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{2}
}

func (x *CountryRewardConfig) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CountryRewardConfig) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CountryRewardConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CountryRewardConfig) GetReferrerReward() int32 {
	if x != nil {
		return x.ReferrerReward
	}
	return 0
}

func (x *CountryRewardConfig) GetRefereeReward() int32 {
	if x != nil {
		return x.RefereeReward
	}
	return 0
}

func (x *CountryRewardConfig) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CountryRewardConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CountryRewardConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ReferralStats message represents aggregated referral statistics
type ReferralStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalReferrals     int64                  `protobuf:"varint,1,opt,name=total_referrals,json=totalReferrals,proto3" json:"total_referrals,omitempty"`
	TotalRewardsEarned int32                  `protobuf:"varint,2,opt,name=total_rewards_earned,json=totalRewardsEarned,proto3" json:"total_rewards_earned,omitempty"`
	PendingRewards     int32                  `protobuf:"varint,3,opt,name=pending_rewards,json=pendingRewards,proto3" json:"pending_rewards,omitempty"`
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReferralStats) Reset() {
	*x = ReferralStats{}
	mi := &file_referral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralStats) ProtoMessage() {}

func (x *ReferralStats) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralStats.ProtoReflect.Descriptor instead.
func (*ReferralStats) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{3}
}

func (x *ReferralStats) GetTotalReferrals() int64 {
	if x != nil {
		return x.TotalReferrals
	}
	return 0
}

func (x *ReferralStats) GetTotalRewardsEarned() int32 {
	if x != nil {
		return x.TotalRewardsEarned
	}
	return 0
}

func (x *ReferralStats) GetPendingRewards() int32 {
	if x != nil {
		return x.PendingRewards
	}
	return 0
}

func (x *ReferralStats) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// LeaderboardEntry message represents a top referrer
type LeaderboardEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username       string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	TotalReferrals int64                  `protobuf:"varint,5,opt,name=total_referrals,json=totalReferrals,proto3" json:"total_referrals,omitempty"`
	Rank           int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_referral_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardEntry) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaderboardEntry) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *LeaderboardEntry) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetTotalReferrals() int64 {
	if x != nil {
		return x.TotalReferrals
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// Request/Response messages for ValidateReferralCode
type ValidateReferralCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReferralCodeRequest) Reset() {
	*x = ValidateReferralCodeRequest{}
	mi := &file_referral_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReferralCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReferralCodeRequest) ProtoMessage() {}

func (x *ValidateReferralCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReferralCodeRequest.ProtoReflect.Descriptor instead.
func (*ValidateReferralCodeRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateReferralCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ValidateReferralCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReferralCodeResponse) Reset() {
	*x = ValidateReferralCodeResponse{}
	mi := &file_referral_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReferralCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReferralCodeResponse) ProtoMessage() {}

func (x *ValidateReferralCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReferralCodeResponse.ProtoReflect.Descriptor instead.
func (*ValidateReferralCodeResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateReferralCodeResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateReferralCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages for GetMyReferralCode
type GetMyReferralCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralCodeRequest) Reset() {
	*x = GetMyReferralCodeRequest{}
	mi := &file_referral_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralCodeRequest) ProtoMessage() {}

func (x *GetMyReferralCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralCodeRequest.ProtoReflect.Descriptor instead.
func (*GetMyReferralCodeRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{7}
}

type GetMyReferralCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  *ReferralCode          `protobuf:"bytes,1,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralCodeResponse) Reset() {
	*x = GetMyReferralCodeResponse{}
	mi := &file_referral_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralCodeResponse) ProtoMessage() {}

func (x *GetMyReferralCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralCodeResponse.ProtoReflect.Descriptor instead.
func (*GetMyReferralCodeResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{8}
}

func (x *GetMyReferralCodeResponse) GetReferralCode() *ReferralCode {
	if x != nil {
		return x.ReferralCode
	}
	return nil
}

// Request/Response messages for GetMyReferralStats
type GetMyReferralStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralStatsRequest) Reset() {
	*x = GetMyReferralStatsRequest{}
	mi := &file_referral_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralStatsRequest) ProtoMessage() {}

func (x *GetMyReferralStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMyReferralStatsRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{9}
}

type GetMyReferralStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ReferralStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralStatsResponse) Reset() {
	*x = GetMyReferralStatsResponse{}
	mi := &file_referral_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralStatsResponse) ProtoMessage() {}

func (x *GetMyReferralStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMyReferralStatsResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyReferralStatsResponse) GetStats() *ReferralStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Request/Response messages for GetMyReferrals
type GetMyReferralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralsRequest) Reset() {
	*x = GetMyReferralsRequest{}
	mi := &file_referral_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralsRequest) ProtoMessage() {}

func (x *GetMyReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralsRequest.ProtoReflect.Descriptor instead.
func (*GetMyReferralsRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{11}
}

func (x *GetMyReferralsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyReferralsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyReferralsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrals     []*ReferralTransaction `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReferralsResponse) Reset() {
	*x = GetMyReferralsResponse{}
	mi := &file_referral_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReferralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReferralsResponse) ProtoMessage() {}

func (x *GetMyReferralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReferralsResponse.ProtoReflect.Descriptor instead.
func (*GetMyReferralsResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyReferralsResponse) GetReferrals() []*ReferralTransaction {
	if x != nil {
		return x.Referrals
	}
	return nil
}

func (x *GetMyReferralsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyReferralsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request/Response messages for GetReferralLeaderboard
type GetReferralLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralLeaderboardRequest) Reset() {
	*x = GetReferralLeaderboardRequest{}
	mi := &file_referral_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralLeaderboardRequest) ProtoMessage() {}

func (x *GetReferralLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetReferralLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{13}
}

func (x *GetReferralLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetReferralLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralLeaderboardResponse) Reset() {
	*x = GetReferralLeaderboardResponse{}
	mi := &file_referral_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralLeaderboardResponse) ProtoMessage() {}

func (x *GetReferralLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetReferralLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{14}
}

func (x *GetReferralLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Request/Response messages for GetCountryRewardConfig
type GetCountryRewardConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryRewardConfigRequest) Reset() {
	*x = GetCountryRewardConfigRequest{}
	mi := &file_referral_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryRewardConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRewardConfigRequest) ProtoMessage() {}

func (x *GetCountryRewardConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRewardConfigRequest.ProtoReflect.Descriptor instead.
func (*GetCountryRewardConfigRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{15}
}

func (x *GetCountryRewardConfigRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type GetCountryRewardConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CountryRewardConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryRewardConfigResponse) Reset() {
	*x = GetCountryRewardConfigResponse{}
	mi := &file_referral_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryRewardConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRewardConfigResponse) ProtoMessage() {}

func (x *GetCountryRewardConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRewardConfigResponse.ProtoReflect.Descriptor instead.
func (*GetCountryRewardConfigResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{16}
}

func (x *GetCountryRewardConfigResponse) GetConfig() *CountryRewardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Request/Response messages for RecordReferral
type RecordReferralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefereeUserId uint64                 `protobuf:"varint,1,opt,name=referee_user_id,json=refereeUserId,proto3" json:"referee_user_id,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,2,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordReferralRequest) Reset() {
	*x = RecordReferralRequest{}
	mi := &file_referral_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReferralRequest) ProtoMessage() {}

func (x *RecordReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReferralRequest.ProtoReflect.Descriptor instead.
func (*RecordReferralRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{17}
}

func (x *RecordReferralRequest) GetRefereeUserId() uint64 {
	if x != nil {
		return x.RefereeUserId
	}
	return 0
}

func (x *RecordReferralRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type RecordReferralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Transaction   *ReferralTransaction   `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordReferralResponse) Reset() {
	*x = RecordReferralResponse{}
	mi := &file_referral_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordReferralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReferralResponse) ProtoMessage() {}

func (x *RecordReferralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReferralResponse.ProtoReflect.Descriptor instead.
func (*RecordReferralResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{18}
}

func (x *RecordReferralResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordReferralResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordReferralResponse) GetTransaction() *ReferralTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Request/Response messages for CreditReferralRewards
type CreditReferralRewardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint64                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditReferralRewardsRequest) Reset() {
	*x = CreditReferralRewardsRequest{}
	mi := &file_referral_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditReferralRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditReferralRewardsRequest) ProtoMessage() {}

func (x *CreditReferralRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditReferralRewardsRequest.ProtoReflect.Descriptor instead.
func (*CreditReferralRewardsRequest) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{19}
}

func (x *CreditReferralRewardsRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type CreditReferralRewardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditReferralRewardsResponse) Reset() {
	*x = CreditReferralRewardsResponse{}
	mi := &file_referral_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditReferralRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditReferralRewardsResponse) ProtoMessage() {}

func (x *CreditReferralRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditReferralRewardsResponse.ProtoReflect.Descriptor instead.
func (*CreditReferralRewardsResponse) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{20}
}

func (x *CreditReferralRewardsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreditReferralRewardsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_referral_proto protoreflect.FileDescriptor

const file_referral_proto_rawDesc = "" +
	"\n" +
	"\x0ereferral.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xde\x01\n" +
	"\fReferralCode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf8\x03\n" +
	"\x13ReferralTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x10referrer_user_id\x18\x02 \x01(\x04R\x0ereferrerUserId\x12&\n" +
	"\x0freferee_user_id\x18\x03 \x01(\x04R\rrefereeUserId\x12,\n" +
	"\x12referral_code_used\x18\x04 \x01(\tR\x10referralCodeUsed\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.pb.ReferralStatusR\x06status\x124\n" +
	"\x16referrer_reward_amount\x18\x06 \x01(\x05R\x14referrerRewardAmount\x122\n" +
	"\x15referee_reward_amount\x18\a \x01(\x05R\x13refereeRewardAmount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12%\n" +
	"\x0efailure_reason\x18\v \x01(\tR\rfailureReason\"\xc7\x02\n" +
	"\x13CountryRewardConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0freferrer_reward\x18\x04 \x01(\x05R\x0ereferrerReward\x12%\n" +
	"\x0ereferee_reward\x18\x05 \x01(\x05R\rrefereeReward\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x01\n" +
	"\rReferralStats\x12'\n" +
	"\x0ftotal_referrals\x18\x01 \x01(\x03R\x0etotalReferrals\x120\n" +
	"\x14total_rewards_earned\x18\x02 \x01(\x05R\x12totalRewardsEarned\x12'\n" +
	"\x0fpending_rewards\x18\x03 \x01(\x05R\x0ependingRewards\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xc0\x01\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12'\n" +
	"\x0ftotal_referrals\x18\x05 \x01(\x03R\x0etotalReferrals\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\"1\n" +
	"\x1bValidateReferralCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"S\n" +
	"\x1cValidateReferralCodeResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetMyReferralCodeRequest\"R\n" +
	"\x19GetMyReferralCodeResponse\x125\n" +
	"\rreferral_code\x18\x01 \x01(\v2\x10.pb.ReferralCodeR\freferralCode\"\x1b\n" +
	"\x19GetMyReferralStatsRequest\"E\n" +
	"\x1aGetMyReferralStatsResponse\x12'\n" +
	"\x05stats\x18\x01 \x01(\v2\x11.pb.ReferralStatsR\x05stats\"H\n" +
	"\x15GetMyReferralsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x80\x01\n" +
	"\x16GetMyReferralsResponse\x125\n" +
	"\treferrals\x18\x01 \x03(\v2\x17.pb.ReferralTransactionR\treferrals\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"5\n" +
	"\x1dGetReferralLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"P\n" +
	"\x1eGetReferralLeaderboardResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.pb.LeaderboardEntryR\aentries\"B\n" +
	"\x1dGetCountryRewardConfigRequest\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\"Q\n" +
	"\x1eGetCountryRewardConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.pb.CountryRewardConfigR\x06config\"d\n" +
	"\x15RecordReferralRequest\x12&\n" +
	"\x0freferee_user_id\x18\x01 \x01(\x04R\rrefereeUserId\x12#\n" +
	"\rreferral_code\x18\x02 \x01(\tR\freferralCode\"\x87\x01\n" +
	"\x16RecordReferralResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\vtransaction\x18\x03 \x01(\v2\x17.pb.ReferralTransactionR\vtransaction\"E\n" +
	"\x1cCreditReferralRewardsRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x04R\rtransactionId\"S\n" +
	"\x1dCreditReferralRewardsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x87\x01\n" +
	"\x0eReferralStatus\x12\x1b\n" +
	"\x17REFERRAL_STATUS_PENDING\x10\x00\x12\x1d\n" +
	"\x19REFERRAL_STATUS_COMPLETED\x10\x01\x12\x1a\n" +
	"\x16REFERRAL_STATUS_FAILED\x10\x02\x12\x1d\n" +
	"\x19REFERRAL_STATUS_CANCELLED\x10\x032\xe8\a\n" +
	"\x0fReferralService\x12{\n" +
	"\x14ValidateReferralCode\x12\x1f.pb.ValidateReferralCodeRequest\x1a .pb.ValidateReferralCodeResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/referral/validate\x12n\n" +
	"\x11GetMyReferralCode\x12\x1c.pb.GetMyReferralCodeRequest\x1a\x1d.pb.GetMyReferralCodeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/referral/my-code\x12r\n" +
	"\x12GetMyReferralStats\x12\x1d.pb.GetMyReferralStatsRequest\x1a\x1e.pb.GetMyReferralStatsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/referral/my-stats\x12j\n" +
	"\x0eGetMyReferrals\x12\x19.pb.GetMyReferralsRequest\x1a\x1a.pb.GetMyReferralsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/referral/my-referrals\x12\x81\x01\n" +
	"\x16GetReferralLeaderboard\x12!.pb.GetReferralLeaderboardRequest\x1a\".pb.GetReferralLeaderboardResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/referral/leaderboard\x12\x93\x01\n" +
	"\x16GetCountryRewardConfig\x12!.pb.GetCountryRewardConfigRequest\x1a\".pb.GetCountryRewardConfigResponse\"2\x82\xd3\xe4\x93\x02,\x12*/v1/referral/country-config/{country_code}\x12g\n" +
	"\x0eRecordReferral\x12\x19.pb.RecordReferralRequest\x1a\x1a.pb.RecordReferralResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/referral/record\x12\x84\x01\n" +
	"\x15CreditReferralRewards\x12 .pb.CreditReferralRewardsRequest\x1a!.pb.CreditReferralRewardsResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/referral/credit-rewardsB\xf3\x01\x92A\xde\x01\x12s\n" +
	"\x1bLazerVault Referral Service\"O\n" +
	"\x12LazerVault Support\x12\x1dhttps://github.com/LazerVault\x1a\x1asupport@lazervault.example2\x031.0ZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x0flazervaultGo/pbb\x06proto3"

var (
	file_referral_proto_rawDescOnce sync.Once
	file_referral_proto_rawDescData []byte
)

func file_referral_proto_rawDescGZIP() []byte {
	file_referral_proto_rawDescOnce.Do(func() {
		file_referral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_referral_proto_rawDesc), len(file_referral_proto_rawDesc)))
	})
	return file_referral_proto_rawDescData
}

var file_referral_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_referral_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_referral_proto_goTypes = []any{
	(ReferralStatus)(0),                    // 0: pb.ReferralStatus
	(*ReferralCode)(nil),                   // 1: pb.ReferralCode
	(*ReferralTransaction)(nil),            // 2: pb.ReferralTransaction
	(*CountryRewardConfig)(nil),            // 3: pb.CountryRewardConfig
	(*ReferralStats)(nil),                  // 4: pb.ReferralStats
	(*LeaderboardEntry)(nil),               // 5: pb.LeaderboardEntry
	(*ValidateReferralCodeRequest)(nil),    // 6: pb.ValidateReferralCodeRequest
	(*ValidateReferralCodeResponse)(nil),   // 7: pb.ValidateReferralCodeResponse
	(*GetMyReferralCodeRequest)(nil),       // 8: pb.GetMyReferralCodeRequest
	(*GetMyReferralCodeResponse)(nil),      // 9: pb.GetMyReferralCodeResponse
	(*GetMyReferralStatsRequest)(nil),      // 10: pb.GetMyReferralStatsRequest
	(*GetMyReferralStatsResponse)(nil),     // 11: pb.GetMyReferralStatsResponse
	(*GetMyReferralsRequest)(nil),          // 12: pb.GetMyReferralsRequest
	(*GetMyReferralsResponse)(nil),         // 13: pb.GetMyReferralsResponse
	(*GetReferralLeaderboardRequest)(nil),  // 14: pb.GetReferralLeaderboardRequest
	(*GetReferralLeaderboardResponse)(nil), // 15: pb.GetReferralLeaderboardResponse
	(*GetCountryRewardConfigRequest)(nil),  // 16: pb.GetCountryRewardConfigRequest
	(*GetCountryRewardConfigResponse)(nil), // 17: pb.GetCountryRewardConfigResponse
	(*RecordReferralRequest)(nil),          // 18: pb.RecordReferralRequest
	(*RecordReferralResponse)(nil),         // 19: pb.RecordReferralResponse
	(*CreditReferralRewardsRequest)(nil),   // 20: pb.CreditReferralRewardsRequest
	(*CreditReferralRewardsResponse)(nil),  // 21: pb.CreditReferralRewardsResponse
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
}
var file_referral_proto_depIdxs = []int32{
	22, // 0: pb.ReferralCode.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: pb.ReferralCode.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: pb.ReferralTransaction.status:type_name -> pb.ReferralStatus
	22, // 3: pb.ReferralTransaction.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: pb.ReferralTransaction.completed_at:type_name -> google.protobuf.Timestamp
	22, // 5: pb.CountryRewardConfig.created_at:type_name -> google.protobuf.Timestamp
	22, // 6: pb.CountryRewardConfig.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: pb.GetMyReferralCodeResponse.referral_code:type_name -> pb.ReferralCode
	4,  // 8: pb.GetMyReferralStatsResponse.stats:type_name -> pb.ReferralStats
	2,  // 9: pb.GetMyReferralsResponse.referrals:type_name -> pb.ReferralTransaction
	5,  // 10: pb.GetReferralLeaderboardResponse.entries:type_name -> pb.LeaderboardEntry
	3,  // 11: pb.GetCountryRewardConfigResponse.config:type_name -> pb.CountryRewardConfig
	2,  // 12: pb.RecordReferralResponse.transaction:type_name -> pb.ReferralTransaction
	6,  // 13: pb.ReferralService.ValidateReferralCode:input_type -> pb.ValidateReferralCodeRequest
	8,  // 14: pb.ReferralService.GetMyReferralCode:input_type -> pb.GetMyReferralCodeRequest
	10, // 15: pb.ReferralService.GetMyReferralStats:input_type -> pb.GetMyReferralStatsRequest
	12, // 16: pb.ReferralService.GetMyReferrals:input_type -> pb.GetMyReferralsRequest
	14, // 17: pb.ReferralService.GetReferralLeaderboard:input_type -> pb.GetReferralLeaderboardRequest
	16, // 18: pb.ReferralService.GetCountryRewardConfig:input_type -> pb.GetCountryRewardConfigRequest
	18, // 19: pb.ReferralService.RecordReferral:input_type -> pb.RecordReferralRequest
	20, // 20: pb.ReferralService.CreditReferralRewards:input_type -> pb.CreditReferralRewardsRequest
	7,  // 21: pb.ReferralService.ValidateReferralCode:output_type -> pb.ValidateReferralCodeResponse
	9,  // 22: pb.ReferralService.GetMyReferralCode:output_type -> pb.GetMyReferralCodeResponse
	11, // 23: pb.ReferralService.GetMyReferralStats:output_type -> pb.GetMyReferralStatsResponse
	13, // 24: pb.ReferralService.GetMyReferrals:output_type -> pb.GetMyReferralsResponse
	15, // 25: pb.ReferralService.GetReferralLeaderboard:output_type -> pb.GetReferralLeaderboardResponse
	17, // 26: pb.ReferralService.GetCountryRewardConfig:output_type -> pb.GetCountryRewardConfigResponse
	19, // 27: pb.ReferralService.RecordReferral:output_type -> pb.RecordReferralResponse
	21, // 28: pb.ReferralService.CreditReferralRewards:output_type -> pb.CreditReferralRewardsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_referral_proto_init() }
func file_referral_proto_init() {
	if File_referral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_referral_proto_rawDesc), len(file_referral_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_referral_proto_goTypes,
		DependencyIndexes: file_referral_proto_depIdxs,
		EnumInfos:         file_referral_proto_enumTypes,
		MessageInfos:      file_referral_proto_msgTypes,
	}.Build()
	File_referral_proto = out.File
	file_referral_proto_goTypes = nil
	file_referral_proto_depIdxs = nil
}
