// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: statistics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_CreateExpense_FullMethodName                     = "/pb.StatisticsService/CreateExpense"
	StatisticsService_GetExpenses_FullMethodName                       = "/pb.StatisticsService/GetExpenses"
	StatisticsService_GetExpenseById_FullMethodName                    = "/pb.StatisticsService/GetExpenseById"
	StatisticsService_UpdateExpense_FullMethodName                     = "/pb.StatisticsService/UpdateExpense"
	StatisticsService_DeleteExpense_FullMethodName                     = "/pb.StatisticsService/DeleteExpense"
	StatisticsService_CreateBudget_FullMethodName                      = "/pb.StatisticsService/CreateBudget"
	StatisticsService_GetBudgets_FullMethodName                        = "/pb.StatisticsService/GetBudgets"
	StatisticsService_GetBudgetById_FullMethodName                     = "/pb.StatisticsService/GetBudgetById"
	StatisticsService_UpdateBudget_FullMethodName                      = "/pb.StatisticsService/UpdateBudget"
	StatisticsService_DeleteBudget_FullMethodName                      = "/pb.StatisticsService/DeleteBudget"
	StatisticsService_GetSpendingAnalytics_FullMethodName              = "/pb.StatisticsService/GetSpendingAnalytics"
	StatisticsService_GetCategoryBreakdown_FullMethodName              = "/pb.StatisticsService/GetCategoryBreakdown"
	StatisticsService_GetBudgetProgress_FullMethodName                 = "/pb.StatisticsService/GetBudgetProgress"
	StatisticsService_GetSpendingTrends_FullMethodName                 = "/pb.StatisticsService/GetSpendingTrends"
	StatisticsService_GetBudgetAlerts_FullMethodName                   = "/pb.StatisticsService/GetBudgetAlerts"
	StatisticsService_MarkAlertAsRead_FullMethodName                   = "/pb.StatisticsService/MarkAlertAsRead"
	StatisticsService_GetAISpendingInsights_FullMethodName             = "/pb.StatisticsService/GetAISpendingInsights"
	StatisticsService_GetAIBudgetingRecommendations_FullMethodName     = "/pb.StatisticsService/GetAIBudgetingRecommendations"
	StatisticsService_AutoCategorizeExpense_FullMethodName             = "/pb.StatisticsService/AutoCategorizeExpense"
	StatisticsService_GetAIFinancialAdvice_FullMethodName              = "/pb.StatisticsService/GetAIFinancialAdvice"
	StatisticsService_GetIncomeSources_FullMethodName                  = "/pb.StatisticsService/GetIncomeSources"
	StatisticsService_GetIncomeBreakdown_FullMethodName                = "/pb.StatisticsService/GetIncomeBreakdown"
	StatisticsService_CreateIncomeSource_FullMethodName                = "/pb.StatisticsService/CreateIncomeSource"
	StatisticsService_GetInvestmentPortfolio_FullMethodName            = "/pb.StatisticsService/GetInvestmentPortfolio"
	StatisticsService_CreateInvestment_FullMethodName                  = "/pb.StatisticsService/CreateInvestment"
	StatisticsService_GetFinancialGoals_FullMethodName                 = "/pb.StatisticsService/GetFinancialGoals"
	StatisticsService_CreateFinancialGoal_FullMethodName               = "/pb.StatisticsService/CreateFinancialGoal"
	StatisticsService_UpdateFinancialGoalProgress_FullMethodName       = "/pb.StatisticsService/UpdateFinancialGoalProgress"
	StatisticsService_GetSavingsGoal_FullMethodName                    = "/pb.StatisticsService/GetSavingsGoal"
	StatisticsService_CreateOrUpdateSavingsGoal_FullMethodName         = "/pb.StatisticsService/CreateOrUpdateSavingsGoal"
	StatisticsService_GetUpcomingBills_FullMethodName                  = "/pb.StatisticsService/GetUpcomingBills"
	StatisticsService_CreateRecurringBill_FullMethodName               = "/pb.StatisticsService/CreateRecurringBill"
	StatisticsService_GetTrackedIncome_FullMethodName                  = "/pb.StatisticsService/GetTrackedIncome"
	StatisticsService_GetTrackedExpenditure_FullMethodName             = "/pb.StatisticsService/GetTrackedExpenditure"
	StatisticsService_GetTrackedIncomeBreakdown_FullMethodName         = "/pb.StatisticsService/GetTrackedIncomeBreakdown"
	StatisticsService_GetTrackedExpenditureBreakdown_FullMethodName    = "/pb.StatisticsService/GetTrackedExpenditureBreakdown"
	StatisticsService_GetTrackedIncomeTransactions_FullMethodName      = "/pb.StatisticsService/GetTrackedIncomeTransactions"
	StatisticsService_GetTrackedExpenditureTransactions_FullMethodName = "/pb.StatisticsService/GetTrackedExpenditureTransactions"
	StatisticsService_GetComprehensiveFinancialSummary_FullMethodName  = "/pb.StatisticsService/GetComprehensiveFinancialSummary"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	// Expense Management
	CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*CreateExpenseResponse, error)
	GetExpenses(ctx context.Context, in *GetExpensesRequest, opts ...grpc.CallOption) (*GetExpensesResponse, error)
	GetExpenseById(ctx context.Context, in *GetExpenseByIdRequest, opts ...grpc.CallOption) (*GetExpenseByIdResponse, error)
	UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*UpdateExpenseResponse, error)
	DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error)
	// Budget Management
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error)
	GetBudgets(ctx context.Context, in *GetBudgetsRequest, opts ...grpc.CallOption) (*GetBudgetsResponse, error)
	GetBudgetById(ctx context.Context, in *GetBudgetByIdRequest, opts ...grpc.CallOption) (*GetBudgetByIdResponse, error)
	UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*UpdateBudgetResponse, error)
	DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*DeleteBudgetResponse, error)
	// Analytics & Reports
	GetSpendingAnalytics(ctx context.Context, in *GetSpendingAnalyticsRequest, opts ...grpc.CallOption) (*GetSpendingAnalyticsResponse, error)
	GetCategoryBreakdown(ctx context.Context, in *GetCategoryBreakdownRequest, opts ...grpc.CallOption) (*GetCategoryBreakdownResponse, error)
	GetBudgetProgress(ctx context.Context, in *GetBudgetProgressRequest, opts ...grpc.CallOption) (*GetBudgetProgressResponse, error)
	GetSpendingTrends(ctx context.Context, in *GetSpendingTrendsRequest, opts ...grpc.CallOption) (*GetSpendingTrendsResponse, error)
	// Notifications
	GetBudgetAlerts(ctx context.Context, in *GetBudgetAlertsRequest, opts ...grpc.CallOption) (*GetBudgetAlertsResponse, error)
	MarkAlertAsRead(ctx context.Context, in *MarkAlertAsReadRequest, opts ...grpc.CallOption) (*MarkAlertAsReadResponse, error)
	// AI-Powered Statistics
	GetAISpendingInsights(ctx context.Context, in *GetAISpendingInsightsRequest, opts ...grpc.CallOption) (*GetAISpendingInsightsResponse, error)
	GetAIBudgetingRecommendations(ctx context.Context, in *GetAIBudgetingRecommendationsRequest, opts ...grpc.CallOption) (*GetAIBudgetingRecommendationsResponse, error)
	AutoCategorizeExpense(ctx context.Context, in *AutoCategorizeExpenseRequest, opts ...grpc.CallOption) (*AutoCategorizeExpenseResponse, error)
	GetAIFinancialAdvice(ctx context.Context, in *GetAIFinancialAdviceRequest, opts ...grpc.CallOption) (*GetAIFinancialAdviceResponse, error)
	// Income Management
	GetIncomeSources(ctx context.Context, in *GetIncomeSourcesRequest, opts ...grpc.CallOption) (*GetIncomeSourcesResponse, error)
	GetIncomeBreakdown(ctx context.Context, in *GetIncomeBreakdownRequest, opts ...grpc.CallOption) (*GetIncomeBreakdownResponse, error)
	CreateIncomeSource(ctx context.Context, in *CreateIncomeSourceRequest, opts ...grpc.CallOption) (*CreateIncomeSourceResponse, error)
	// Investment Management
	GetInvestmentPortfolio(ctx context.Context, in *GetInvestmentPortfolioRequest, opts ...grpc.CallOption) (*GetInvestmentPortfolioResponse, error)
	CreateInvestment(ctx context.Context, in *CreateInvestmentRequest, opts ...grpc.CallOption) (*CreateInvestmentResponse, error)
	// Financial Goals Management
	GetFinancialGoals(ctx context.Context, in *GetFinancialGoalsRequest, opts ...grpc.CallOption) (*GetFinancialGoalsResponse, error)
	CreateFinancialGoal(ctx context.Context, in *CreateFinancialGoalRequest, opts ...grpc.CallOption) (*CreateFinancialGoalResponse, error)
	UpdateFinancialGoalProgress(ctx context.Context, in *UpdateFinancialGoalProgressRequest, opts ...grpc.CallOption) (*UpdateFinancialGoalProgressResponse, error)
	// Savings Goal Management
	GetSavingsGoal(ctx context.Context, in *GetSavingsGoalRequest, opts ...grpc.CallOption) (*GetSavingsGoalResponse, error)
	CreateOrUpdateSavingsGoal(ctx context.Context, in *CreateOrUpdateSavingsGoalRequest, opts ...grpc.CallOption) (*CreateOrUpdateSavingsGoalResponse, error)
	// Recurring Bills Management
	GetUpcomingBills(ctx context.Context, in *GetUpcomingBillsRequest, opts ...grpc.CallOption) (*GetUpcomingBillsResponse, error)
	CreateRecurringBill(ctx context.Context, in *CreateRecurringBillRequest, opts ...grpc.CallOption) (*CreateRecurringBillResponse, error)
	// Tracked Transaction Methods
	GetTrackedIncome(ctx context.Context, in *GetTrackedIncomeRequest, opts ...grpc.CallOption) (*GetTrackedIncomeResponse, error)
	GetTrackedExpenditure(ctx context.Context, in *GetTrackedExpenditureRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureResponse, error)
	GetTrackedIncomeBreakdown(ctx context.Context, in *GetTrackedIncomeBreakdownRequest, opts ...grpc.CallOption) (*GetTrackedIncomeBreakdownResponse, error)
	GetTrackedExpenditureBreakdown(ctx context.Context, in *GetTrackedExpenditureBreakdownRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureBreakdownResponse, error)
	GetTrackedIncomeTransactions(ctx context.Context, in *GetTrackedIncomeTransactionsRequest, opts ...grpc.CallOption) (*GetTrackedIncomeTransactionsResponse, error)
	GetTrackedExpenditureTransactions(ctx context.Context, in *GetTrackedExpenditureTransactionsRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureTransactionsResponse, error)
	GetComprehensiveFinancialSummary(ctx context.Context, in *GetComprehensiveFinancialSummaryRequest, opts ...grpc.CallOption) (*GetComprehensiveFinancialSummaryResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*CreateExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExpenseResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetExpenses(ctx context.Context, in *GetExpensesRequest, opts ...grpc.CallOption) (*GetExpensesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpensesResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetExpenses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetExpenseById(ctx context.Context, in *GetExpenseByIdRequest, opts ...grpc.CallOption) (*GetExpenseByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpenseByIdResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetExpenseById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*UpdateExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateExpenseResponse)
	err := c.cc.Invoke(ctx, StatisticsService_UpdateExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExpenseResponse)
	err := c.cc.Invoke(ctx, StatisticsService_DeleteExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBudgetResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetBudgets(ctx context.Context, in *GetBudgetsRequest, opts ...grpc.CallOption) (*GetBudgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetBudgetById(ctx context.Context, in *GetBudgetByIdRequest, opts ...grpc.CallOption) (*GetBudgetByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetByIdResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetBudgetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*UpdateBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBudgetResponse)
	err := c.cc.Invoke(ctx, StatisticsService_UpdateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*DeleteBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBudgetResponse)
	err := c.cc.Invoke(ctx, StatisticsService_DeleteBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetSpendingAnalytics(ctx context.Context, in *GetSpendingAnalyticsRequest, opts ...grpc.CallOption) (*GetSpendingAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpendingAnalyticsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetSpendingAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetCategoryBreakdown(ctx context.Context, in *GetCategoryBreakdownRequest, opts ...grpc.CallOption) (*GetCategoryBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryBreakdownResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetCategoryBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetBudgetProgress(ctx context.Context, in *GetBudgetProgressRequest, opts ...grpc.CallOption) (*GetBudgetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetProgressResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetBudgetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetSpendingTrends(ctx context.Context, in *GetSpendingTrendsRequest, opts ...grpc.CallOption) (*GetSpendingTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpendingTrendsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetSpendingTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetBudgetAlerts(ctx context.Context, in *GetBudgetAlertsRequest, opts ...grpc.CallOption) (*GetBudgetAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetAlertsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetBudgetAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) MarkAlertAsRead(ctx context.Context, in *MarkAlertAsReadRequest, opts ...grpc.CallOption) (*MarkAlertAsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAlertAsReadResponse)
	err := c.cc.Invoke(ctx, StatisticsService_MarkAlertAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetAISpendingInsights(ctx context.Context, in *GetAISpendingInsightsRequest, opts ...grpc.CallOption) (*GetAISpendingInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAISpendingInsightsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetAISpendingInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetAIBudgetingRecommendations(ctx context.Context, in *GetAIBudgetingRecommendationsRequest, opts ...grpc.CallOption) (*GetAIBudgetingRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIBudgetingRecommendationsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetAIBudgetingRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) AutoCategorizeExpense(ctx context.Context, in *AutoCategorizeExpenseRequest, opts ...grpc.CallOption) (*AutoCategorizeExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoCategorizeExpenseResponse)
	err := c.cc.Invoke(ctx, StatisticsService_AutoCategorizeExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetAIFinancialAdvice(ctx context.Context, in *GetAIFinancialAdviceRequest, opts ...grpc.CallOption) (*GetAIFinancialAdviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIFinancialAdviceResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetAIFinancialAdvice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetIncomeSources(ctx context.Context, in *GetIncomeSourcesRequest, opts ...grpc.CallOption) (*GetIncomeSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncomeSourcesResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetIncomeSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetIncomeBreakdown(ctx context.Context, in *GetIncomeBreakdownRequest, opts ...grpc.CallOption) (*GetIncomeBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncomeBreakdownResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetIncomeBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateIncomeSource(ctx context.Context, in *CreateIncomeSourceRequest, opts ...grpc.CallOption) (*CreateIncomeSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIncomeSourceResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateIncomeSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetInvestmentPortfolio(ctx context.Context, in *GetInvestmentPortfolioRequest, opts ...grpc.CallOption) (*GetInvestmentPortfolioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvestmentPortfolioResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetInvestmentPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateInvestment(ctx context.Context, in *CreateInvestmentRequest, opts ...grpc.CallOption) (*CreateInvestmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvestmentResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateInvestment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetFinancialGoals(ctx context.Context, in *GetFinancialGoalsRequest, opts ...grpc.CallOption) (*GetFinancialGoalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFinancialGoalsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetFinancialGoals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateFinancialGoal(ctx context.Context, in *CreateFinancialGoalRequest, opts ...grpc.CallOption) (*CreateFinancialGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFinancialGoalResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateFinancialGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) UpdateFinancialGoalProgress(ctx context.Context, in *UpdateFinancialGoalProgressRequest, opts ...grpc.CallOption) (*UpdateFinancialGoalProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFinancialGoalProgressResponse)
	err := c.cc.Invoke(ctx, StatisticsService_UpdateFinancialGoalProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetSavingsGoal(ctx context.Context, in *GetSavingsGoalRequest, opts ...grpc.CallOption) (*GetSavingsGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSavingsGoalResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetSavingsGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateOrUpdateSavingsGoal(ctx context.Context, in *CreateOrUpdateSavingsGoalRequest, opts ...grpc.CallOption) (*CreateOrUpdateSavingsGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateSavingsGoalResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateOrUpdateSavingsGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetUpcomingBills(ctx context.Context, in *GetUpcomingBillsRequest, opts ...grpc.CallOption) (*GetUpcomingBillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpcomingBillsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetUpcomingBills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) CreateRecurringBill(ctx context.Context, in *CreateRecurringBillRequest, opts ...grpc.CallOption) (*CreateRecurringBillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecurringBillResponse)
	err := c.cc.Invoke(ctx, StatisticsService_CreateRecurringBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedIncome(ctx context.Context, in *GetTrackedIncomeRequest, opts ...grpc.CallOption) (*GetTrackedIncomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedIncomeResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedExpenditure(ctx context.Context, in *GetTrackedExpenditureRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedExpenditureResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedExpenditure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedIncomeBreakdown(ctx context.Context, in *GetTrackedIncomeBreakdownRequest, opts ...grpc.CallOption) (*GetTrackedIncomeBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedIncomeBreakdownResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedIncomeBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedExpenditureBreakdown(ctx context.Context, in *GetTrackedExpenditureBreakdownRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedExpenditureBreakdownResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedExpenditureBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedIncomeTransactions(ctx context.Context, in *GetTrackedIncomeTransactionsRequest, opts ...grpc.CallOption) (*GetTrackedIncomeTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedIncomeTransactionsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedIncomeTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTrackedExpenditureTransactions(ctx context.Context, in *GetTrackedExpenditureTransactionsRequest, opts ...grpc.CallOption) (*GetTrackedExpenditureTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedExpenditureTransactionsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTrackedExpenditureTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetComprehensiveFinancialSummary(ctx context.Context, in *GetComprehensiveFinancialSummaryRequest, opts ...grpc.CallOption) (*GetComprehensiveFinancialSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComprehensiveFinancialSummaryResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetComprehensiveFinancialSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	// Expense Management
	CreateExpense(context.Context, *CreateExpenseRequest) (*CreateExpenseResponse, error)
	GetExpenses(context.Context, *GetExpensesRequest) (*GetExpensesResponse, error)
	GetExpenseById(context.Context, *GetExpenseByIdRequest) (*GetExpenseByIdResponse, error)
	UpdateExpense(context.Context, *UpdateExpenseRequest) (*UpdateExpenseResponse, error)
	DeleteExpense(context.Context, *DeleteExpenseRequest) (*DeleteExpenseResponse, error)
	// Budget Management
	CreateBudget(context.Context, *CreateBudgetRequest) (*CreateBudgetResponse, error)
	GetBudgets(context.Context, *GetBudgetsRequest) (*GetBudgetsResponse, error)
	GetBudgetById(context.Context, *GetBudgetByIdRequest) (*GetBudgetByIdResponse, error)
	UpdateBudget(context.Context, *UpdateBudgetRequest) (*UpdateBudgetResponse, error)
	DeleteBudget(context.Context, *DeleteBudgetRequest) (*DeleteBudgetResponse, error)
	// Analytics & Reports
	GetSpendingAnalytics(context.Context, *GetSpendingAnalyticsRequest) (*GetSpendingAnalyticsResponse, error)
	GetCategoryBreakdown(context.Context, *GetCategoryBreakdownRequest) (*GetCategoryBreakdownResponse, error)
	GetBudgetProgress(context.Context, *GetBudgetProgressRequest) (*GetBudgetProgressResponse, error)
	GetSpendingTrends(context.Context, *GetSpendingTrendsRequest) (*GetSpendingTrendsResponse, error)
	// Notifications
	GetBudgetAlerts(context.Context, *GetBudgetAlertsRequest) (*GetBudgetAlertsResponse, error)
	MarkAlertAsRead(context.Context, *MarkAlertAsReadRequest) (*MarkAlertAsReadResponse, error)
	// AI-Powered Statistics
	GetAISpendingInsights(context.Context, *GetAISpendingInsightsRequest) (*GetAISpendingInsightsResponse, error)
	GetAIBudgetingRecommendations(context.Context, *GetAIBudgetingRecommendationsRequest) (*GetAIBudgetingRecommendationsResponse, error)
	AutoCategorizeExpense(context.Context, *AutoCategorizeExpenseRequest) (*AutoCategorizeExpenseResponse, error)
	GetAIFinancialAdvice(context.Context, *GetAIFinancialAdviceRequest) (*GetAIFinancialAdviceResponse, error)
	// Income Management
	GetIncomeSources(context.Context, *GetIncomeSourcesRequest) (*GetIncomeSourcesResponse, error)
	GetIncomeBreakdown(context.Context, *GetIncomeBreakdownRequest) (*GetIncomeBreakdownResponse, error)
	CreateIncomeSource(context.Context, *CreateIncomeSourceRequest) (*CreateIncomeSourceResponse, error)
	// Investment Management
	GetInvestmentPortfolio(context.Context, *GetInvestmentPortfolioRequest) (*GetInvestmentPortfolioResponse, error)
	CreateInvestment(context.Context, *CreateInvestmentRequest) (*CreateInvestmentResponse, error)
	// Financial Goals Management
	GetFinancialGoals(context.Context, *GetFinancialGoalsRequest) (*GetFinancialGoalsResponse, error)
	CreateFinancialGoal(context.Context, *CreateFinancialGoalRequest) (*CreateFinancialGoalResponse, error)
	UpdateFinancialGoalProgress(context.Context, *UpdateFinancialGoalProgressRequest) (*UpdateFinancialGoalProgressResponse, error)
	// Savings Goal Management
	GetSavingsGoal(context.Context, *GetSavingsGoalRequest) (*GetSavingsGoalResponse, error)
	CreateOrUpdateSavingsGoal(context.Context, *CreateOrUpdateSavingsGoalRequest) (*CreateOrUpdateSavingsGoalResponse, error)
	// Recurring Bills Management
	GetUpcomingBills(context.Context, *GetUpcomingBillsRequest) (*GetUpcomingBillsResponse, error)
	CreateRecurringBill(context.Context, *CreateRecurringBillRequest) (*CreateRecurringBillResponse, error)
	// Tracked Transaction Methods
	GetTrackedIncome(context.Context, *GetTrackedIncomeRequest) (*GetTrackedIncomeResponse, error)
	GetTrackedExpenditure(context.Context, *GetTrackedExpenditureRequest) (*GetTrackedExpenditureResponse, error)
	GetTrackedIncomeBreakdown(context.Context, *GetTrackedIncomeBreakdownRequest) (*GetTrackedIncomeBreakdownResponse, error)
	GetTrackedExpenditureBreakdown(context.Context, *GetTrackedExpenditureBreakdownRequest) (*GetTrackedExpenditureBreakdownResponse, error)
	GetTrackedIncomeTransactions(context.Context, *GetTrackedIncomeTransactionsRequest) (*GetTrackedIncomeTransactionsResponse, error)
	GetTrackedExpenditureTransactions(context.Context, *GetTrackedExpenditureTransactionsRequest) (*GetTrackedExpenditureTransactionsResponse, error)
	GetComprehensiveFinancialSummary(context.Context, *GetComprehensiveFinancialSummaryRequest) (*GetComprehensiveFinancialSummaryResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) CreateExpense(context.Context, *CreateExpenseRequest) (*CreateExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExpense not implemented")
}
func (UnimplementedStatisticsServiceServer) GetExpenses(context.Context, *GetExpensesRequest) (*GetExpensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpenses not implemented")
}
func (UnimplementedStatisticsServiceServer) GetExpenseById(context.Context, *GetExpenseByIdRequest) (*GetExpenseByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpenseById not implemented")
}
func (UnimplementedStatisticsServiceServer) UpdateExpense(context.Context, *UpdateExpenseRequest) (*UpdateExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExpense not implemented")
}
func (UnimplementedStatisticsServiceServer) DeleteExpense(context.Context, *DeleteExpenseRequest) (*DeleteExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpense not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateBudget(context.Context, *CreateBudgetRequest) (*CreateBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBudget not implemented")
}
func (UnimplementedStatisticsServiceServer) GetBudgets(context.Context, *GetBudgetsRequest) (*GetBudgetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgets not implemented")
}
func (UnimplementedStatisticsServiceServer) GetBudgetById(context.Context, *GetBudgetByIdRequest) (*GetBudgetByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetById not implemented")
}
func (UnimplementedStatisticsServiceServer) UpdateBudget(context.Context, *UpdateBudgetRequest) (*UpdateBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBudget not implemented")
}
func (UnimplementedStatisticsServiceServer) DeleteBudget(context.Context, *DeleteBudgetRequest) (*DeleteBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBudget not implemented")
}
func (UnimplementedStatisticsServiceServer) GetSpendingAnalytics(context.Context, *GetSpendingAnalyticsRequest) (*GetSpendingAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpendingAnalytics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetCategoryBreakdown(context.Context, *GetCategoryBreakdownRequest) (*GetCategoryBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryBreakdown not implemented")
}
func (UnimplementedStatisticsServiceServer) GetBudgetProgress(context.Context, *GetBudgetProgressRequest) (*GetBudgetProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetProgress not implemented")
}
func (UnimplementedStatisticsServiceServer) GetSpendingTrends(context.Context, *GetSpendingTrendsRequest) (*GetSpendingTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpendingTrends not implemented")
}
func (UnimplementedStatisticsServiceServer) GetBudgetAlerts(context.Context, *GetBudgetAlertsRequest) (*GetBudgetAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetAlerts not implemented")
}
func (UnimplementedStatisticsServiceServer) MarkAlertAsRead(context.Context, *MarkAlertAsReadRequest) (*MarkAlertAsReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAlertAsRead not implemented")
}
func (UnimplementedStatisticsServiceServer) GetAISpendingInsights(context.Context, *GetAISpendingInsightsRequest) (*GetAISpendingInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAISpendingInsights not implemented")
}
func (UnimplementedStatisticsServiceServer) GetAIBudgetingRecommendations(context.Context, *GetAIBudgetingRecommendationsRequest) (*GetAIBudgetingRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIBudgetingRecommendations not implemented")
}
func (UnimplementedStatisticsServiceServer) AutoCategorizeExpense(context.Context, *AutoCategorizeExpenseRequest) (*AutoCategorizeExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoCategorizeExpense not implemented")
}
func (UnimplementedStatisticsServiceServer) GetAIFinancialAdvice(context.Context, *GetAIFinancialAdviceRequest) (*GetAIFinancialAdviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIFinancialAdvice not implemented")
}
func (UnimplementedStatisticsServiceServer) GetIncomeSources(context.Context, *GetIncomeSourcesRequest) (*GetIncomeSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeSources not implemented")
}
func (UnimplementedStatisticsServiceServer) GetIncomeBreakdown(context.Context, *GetIncomeBreakdownRequest) (*GetIncomeBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeBreakdown not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateIncomeSource(context.Context, *CreateIncomeSourceRequest) (*CreateIncomeSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIncomeSource not implemented")
}
func (UnimplementedStatisticsServiceServer) GetInvestmentPortfolio(context.Context, *GetInvestmentPortfolioRequest) (*GetInvestmentPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvestmentPortfolio not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateInvestment(context.Context, *CreateInvestmentRequest) (*CreateInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvestment not implemented")
}
func (UnimplementedStatisticsServiceServer) GetFinancialGoals(context.Context, *GetFinancialGoalsRequest) (*GetFinancialGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinancialGoals not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateFinancialGoal(context.Context, *CreateFinancialGoalRequest) (*CreateFinancialGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFinancialGoal not implemented")
}
func (UnimplementedStatisticsServiceServer) UpdateFinancialGoalProgress(context.Context, *UpdateFinancialGoalProgressRequest) (*UpdateFinancialGoalProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinancialGoalProgress not implemented")
}
func (UnimplementedStatisticsServiceServer) GetSavingsGoal(context.Context, *GetSavingsGoalRequest) (*GetSavingsGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavingsGoal not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateOrUpdateSavingsGoal(context.Context, *CreateOrUpdateSavingsGoalRequest) (*CreateOrUpdateSavingsGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateSavingsGoal not implemented")
}
func (UnimplementedStatisticsServiceServer) GetUpcomingBills(context.Context, *GetUpcomingBillsRequest) (*GetUpcomingBillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpcomingBills not implemented")
}
func (UnimplementedStatisticsServiceServer) CreateRecurringBill(context.Context, *CreateRecurringBillRequest) (*CreateRecurringBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecurringBill not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedIncome(context.Context, *GetTrackedIncomeRequest) (*GetTrackedIncomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedIncome not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedExpenditure(context.Context, *GetTrackedExpenditureRequest) (*GetTrackedExpenditureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedExpenditure not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedIncomeBreakdown(context.Context, *GetTrackedIncomeBreakdownRequest) (*GetTrackedIncomeBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedIncomeBreakdown not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedExpenditureBreakdown(context.Context, *GetTrackedExpenditureBreakdownRequest) (*GetTrackedExpenditureBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedExpenditureBreakdown not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedIncomeTransactions(context.Context, *GetTrackedIncomeTransactionsRequest) (*GetTrackedIncomeTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedIncomeTransactions not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTrackedExpenditureTransactions(context.Context, *GetTrackedExpenditureTransactionsRequest) (*GetTrackedExpenditureTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedExpenditureTransactions not implemented")
}
func (UnimplementedStatisticsServiceServer) GetComprehensiveFinancialSummary(context.Context, *GetComprehensiveFinancialSummaryRequest) (*GetComprehensiveFinancialSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComprehensiveFinancialSummary not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_CreateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateExpense(ctx, req.(*CreateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetExpenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetExpenses(ctx, req.(*GetExpensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetExpenseById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpenseByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetExpenseById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetExpenseById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetExpenseById(ctx, req.(*GetExpenseByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_UpdateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).UpdateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_UpdateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).UpdateExpense(ctx, req.(*UpdateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_DeleteExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).DeleteExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_DeleteExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).DeleteExpense(ctx, req.(*DeleteExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetBudgets(ctx, req.(*GetBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetBudgetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetBudgetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetBudgetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetBudgetById(ctx, req.(*GetBudgetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_UpdateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).UpdateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_UpdateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).UpdateBudget(ctx, req.(*UpdateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_DeleteBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).DeleteBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_DeleteBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).DeleteBudget(ctx, req.(*DeleteBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetSpendingAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpendingAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetSpendingAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetSpendingAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetSpendingAnalytics(ctx, req.(*GetSpendingAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetCategoryBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetCategoryBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetCategoryBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetCategoryBreakdown(ctx, req.(*GetCategoryBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetBudgetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetBudgetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetBudgetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetBudgetProgress(ctx, req.(*GetBudgetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetSpendingTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpendingTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetSpendingTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetSpendingTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetSpendingTrends(ctx, req.(*GetSpendingTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetBudgetAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetBudgetAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetBudgetAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetBudgetAlerts(ctx, req.(*GetBudgetAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_MarkAlertAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAlertAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).MarkAlertAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_MarkAlertAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).MarkAlertAsRead(ctx, req.(*MarkAlertAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetAISpendingInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAISpendingInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetAISpendingInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetAISpendingInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetAISpendingInsights(ctx, req.(*GetAISpendingInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetAIBudgetingRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIBudgetingRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetAIBudgetingRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetAIBudgetingRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetAIBudgetingRecommendations(ctx, req.(*GetAIBudgetingRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_AutoCategorizeExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoCategorizeExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).AutoCategorizeExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_AutoCategorizeExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).AutoCategorizeExpense(ctx, req.(*AutoCategorizeExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetAIFinancialAdvice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIFinancialAdviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetAIFinancialAdvice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetAIFinancialAdvice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetAIFinancialAdvice(ctx, req.(*GetAIFinancialAdviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetIncomeSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetIncomeSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetIncomeSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetIncomeSources(ctx, req.(*GetIncomeSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetIncomeBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetIncomeBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetIncomeBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetIncomeBreakdown(ctx, req.(*GetIncomeBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateIncomeSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIncomeSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateIncomeSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateIncomeSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateIncomeSource(ctx, req.(*CreateIncomeSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetInvestmentPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvestmentPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetInvestmentPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetInvestmentPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetInvestmentPortfolio(ctx, req.(*GetInvestmentPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateInvestment(ctx, req.(*CreateInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetFinancialGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinancialGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetFinancialGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetFinancialGoals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetFinancialGoals(ctx, req.(*GetFinancialGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateFinancialGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFinancialGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateFinancialGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateFinancialGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateFinancialGoal(ctx, req.(*CreateFinancialGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_UpdateFinancialGoalProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinancialGoalProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).UpdateFinancialGoalProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_UpdateFinancialGoalProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).UpdateFinancialGoalProgress(ctx, req.(*UpdateFinancialGoalProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetSavingsGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavingsGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetSavingsGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetSavingsGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetSavingsGoal(ctx, req.(*GetSavingsGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateOrUpdateSavingsGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateSavingsGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateOrUpdateSavingsGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateOrUpdateSavingsGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateOrUpdateSavingsGoal(ctx, req.(*CreateOrUpdateSavingsGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetUpcomingBills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpcomingBillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetUpcomingBills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetUpcomingBills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetUpcomingBills(ctx, req.(*GetUpcomingBillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_CreateRecurringBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecurringBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).CreateRecurringBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_CreateRecurringBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).CreateRecurringBill(ctx, req.(*CreateRecurringBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedIncome(ctx, req.(*GetTrackedIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedExpenditure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedExpenditureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedExpenditure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedExpenditure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedExpenditure(ctx, req.(*GetTrackedExpenditureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedIncomeBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedIncomeBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedIncomeBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedIncomeBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedIncomeBreakdown(ctx, req.(*GetTrackedIncomeBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedExpenditureBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedExpenditureBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedExpenditureBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedExpenditureBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedExpenditureBreakdown(ctx, req.(*GetTrackedExpenditureBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedIncomeTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedIncomeTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedIncomeTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedIncomeTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedIncomeTransactions(ctx, req.(*GetTrackedIncomeTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTrackedExpenditureTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedExpenditureTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTrackedExpenditureTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTrackedExpenditureTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTrackedExpenditureTransactions(ctx, req.(*GetTrackedExpenditureTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetComprehensiveFinancialSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComprehensiveFinancialSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetComprehensiveFinancialSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetComprehensiveFinancialSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetComprehensiveFinancialSummary(ctx, req.(*GetComprehensiveFinancialSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpense",
			Handler:    _StatisticsService_CreateExpense_Handler,
		},
		{
			MethodName: "GetExpenses",
			Handler:    _StatisticsService_GetExpenses_Handler,
		},
		{
			MethodName: "GetExpenseById",
			Handler:    _StatisticsService_GetExpenseById_Handler,
		},
		{
			MethodName: "UpdateExpense",
			Handler:    _StatisticsService_UpdateExpense_Handler,
		},
		{
			MethodName: "DeleteExpense",
			Handler:    _StatisticsService_DeleteExpense_Handler,
		},
		{
			MethodName: "CreateBudget",
			Handler:    _StatisticsService_CreateBudget_Handler,
		},
		{
			MethodName: "GetBudgets",
			Handler:    _StatisticsService_GetBudgets_Handler,
		},
		{
			MethodName: "GetBudgetById",
			Handler:    _StatisticsService_GetBudgetById_Handler,
		},
		{
			MethodName: "UpdateBudget",
			Handler:    _StatisticsService_UpdateBudget_Handler,
		},
		{
			MethodName: "DeleteBudget",
			Handler:    _StatisticsService_DeleteBudget_Handler,
		},
		{
			MethodName: "GetSpendingAnalytics",
			Handler:    _StatisticsService_GetSpendingAnalytics_Handler,
		},
		{
			MethodName: "GetCategoryBreakdown",
			Handler:    _StatisticsService_GetCategoryBreakdown_Handler,
		},
		{
			MethodName: "GetBudgetProgress",
			Handler:    _StatisticsService_GetBudgetProgress_Handler,
		},
		{
			MethodName: "GetSpendingTrends",
			Handler:    _StatisticsService_GetSpendingTrends_Handler,
		},
		{
			MethodName: "GetBudgetAlerts",
			Handler:    _StatisticsService_GetBudgetAlerts_Handler,
		},
		{
			MethodName: "MarkAlertAsRead",
			Handler:    _StatisticsService_MarkAlertAsRead_Handler,
		},
		{
			MethodName: "GetAISpendingInsights",
			Handler:    _StatisticsService_GetAISpendingInsights_Handler,
		},
		{
			MethodName: "GetAIBudgetingRecommendations",
			Handler:    _StatisticsService_GetAIBudgetingRecommendations_Handler,
		},
		{
			MethodName: "AutoCategorizeExpense",
			Handler:    _StatisticsService_AutoCategorizeExpense_Handler,
		},
		{
			MethodName: "GetAIFinancialAdvice",
			Handler:    _StatisticsService_GetAIFinancialAdvice_Handler,
		},
		{
			MethodName: "GetIncomeSources",
			Handler:    _StatisticsService_GetIncomeSources_Handler,
		},
		{
			MethodName: "GetIncomeBreakdown",
			Handler:    _StatisticsService_GetIncomeBreakdown_Handler,
		},
		{
			MethodName: "CreateIncomeSource",
			Handler:    _StatisticsService_CreateIncomeSource_Handler,
		},
		{
			MethodName: "GetInvestmentPortfolio",
			Handler:    _StatisticsService_GetInvestmentPortfolio_Handler,
		},
		{
			MethodName: "CreateInvestment",
			Handler:    _StatisticsService_CreateInvestment_Handler,
		},
		{
			MethodName: "GetFinancialGoals",
			Handler:    _StatisticsService_GetFinancialGoals_Handler,
		},
		{
			MethodName: "CreateFinancialGoal",
			Handler:    _StatisticsService_CreateFinancialGoal_Handler,
		},
		{
			MethodName: "UpdateFinancialGoalProgress",
			Handler:    _StatisticsService_UpdateFinancialGoalProgress_Handler,
		},
		{
			MethodName: "GetSavingsGoal",
			Handler:    _StatisticsService_GetSavingsGoal_Handler,
		},
		{
			MethodName: "CreateOrUpdateSavingsGoal",
			Handler:    _StatisticsService_CreateOrUpdateSavingsGoal_Handler,
		},
		{
			MethodName: "GetUpcomingBills",
			Handler:    _StatisticsService_GetUpcomingBills_Handler,
		},
		{
			MethodName: "CreateRecurringBill",
			Handler:    _StatisticsService_CreateRecurringBill_Handler,
		},
		{
			MethodName: "GetTrackedIncome",
			Handler:    _StatisticsService_GetTrackedIncome_Handler,
		},
		{
			MethodName: "GetTrackedExpenditure",
			Handler:    _StatisticsService_GetTrackedExpenditure_Handler,
		},
		{
			MethodName: "GetTrackedIncomeBreakdown",
			Handler:    _StatisticsService_GetTrackedIncomeBreakdown_Handler,
		},
		{
			MethodName: "GetTrackedExpenditureBreakdown",
			Handler:    _StatisticsService_GetTrackedExpenditureBreakdown_Handler,
		},
		{
			MethodName: "GetTrackedIncomeTransactions",
			Handler:    _StatisticsService_GetTrackedIncomeTransactions_Handler,
		},
		{
			MethodName: "GetTrackedExpenditureTransactions",
			Handler:    _StatisticsService_GetTrackedExpenditureTransactions_Handler,
		},
		{
			MethodName: "GetComprehensiveFinancialSummary",
			Handler:    _StatisticsService_GetComprehensiveFinancialSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics.proto",
}
