// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tagged_invoice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaggedInvoiceService_GetTaggedInvoices_FullMethodName               = "/pb.TaggedInvoiceService/GetTaggedInvoices"
	TaggedInvoiceService_GetTaggedInvoicesByStatus_FullMethodName       = "/pb.TaggedInvoiceService/GetTaggedInvoicesByStatus"
	TaggedInvoiceService_GetTaggedInvoiceById_FullMethodName            = "/pb.TaggedInvoiceService/GetTaggedInvoiceById"
	TaggedInvoiceService_GetOverdueTaggedInvoices_FullMethodName        = "/pb.TaggedInvoiceService/GetOverdueTaggedInvoices"
	TaggedInvoiceService_GetUpcomingTaggedInvoices_FullMethodName       = "/pb.TaggedInvoiceService/GetUpcomingTaggedInvoices"
	TaggedInvoiceService_SearchTaggedInvoices_FullMethodName            = "/pb.TaggedInvoiceService/SearchTaggedInvoices"
	TaggedInvoiceService_FilterTaggedInvoicesByPriority_FullMethodName  = "/pb.TaggedInvoiceService/FilterTaggedInvoicesByPriority"
	TaggedInvoiceService_FilterTaggedInvoicesByDateRange_FullMethodName = "/pb.TaggedInvoiceService/FilterTaggedInvoicesByDateRange"
	TaggedInvoiceService_FilterTaggedInvoicesByAmount_FullMethodName    = "/pb.TaggedInvoiceService/FilterTaggedInvoicesByAmount"
	TaggedInvoiceService_MarkTaggedInvoiceAsViewed_FullMethodName       = "/pb.TaggedInvoiceService/MarkTaggedInvoiceAsViewed"
	TaggedInvoiceService_SetInvoicePaymentReminder_FullMethodName       = "/pb.TaggedInvoiceService/SetInvoicePaymentReminder"
	TaggedInvoiceService_RequestTaggedInvoiceDetails_FullMethodName     = "/pb.TaggedInvoiceService/RequestTaggedInvoiceDetails"
	TaggedInvoiceService_GetInvoicePaymentNotifications_FullMethodName  = "/pb.TaggedInvoiceService/GetInvoicePaymentNotifications"
	TaggedInvoiceService_UpdateTaggedInvoiceStatus_FullMethodName       = "/pb.TaggedInvoiceService/UpdateTaggedInvoiceStatus"
	TaggedInvoiceService_DeleteTaggedInvoice_FullMethodName             = "/pb.TaggedInvoiceService/DeleteTaggedInvoice"
	TaggedInvoiceService_MarkMultipleInvoicesAsViewed_FullMethodName    = "/pb.TaggedInvoiceService/MarkMultipleInvoicesAsViewed"
	TaggedInvoiceService_BulkSetPaymentReminders_FullMethodName         = "/pb.TaggedInvoiceService/BulkSetPaymentReminders"
	TaggedInvoiceService_GetTaggedInvoiceStatistics_FullMethodName      = "/pb.TaggedInvoiceService/GetTaggedInvoiceStatistics"
)

// TaggedInvoiceServiceClient is the client API for TaggedInvoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaggedInvoiceServiceClient interface {
	// Core Tagged Invoice Operations
	GetTaggedInvoices(ctx context.Context, in *GetTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetTaggedInvoicesResponse, error)
	GetTaggedInvoicesByStatus(ctx context.Context, in *GetTaggedInvoicesByStatusRequest, opts ...grpc.CallOption) (*GetTaggedInvoicesByStatusResponse, error)
	GetTaggedInvoiceById(ctx context.Context, in *GetTaggedInvoiceByIdRequest, opts ...grpc.CallOption) (*GetTaggedInvoiceByIdResponse, error)
	GetOverdueTaggedInvoices(ctx context.Context, in *GetOverdueTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetOverdueTaggedInvoicesResponse, error)
	GetUpcomingTaggedInvoices(ctx context.Context, in *GetUpcomingTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetUpcomingTaggedInvoicesResponse, error)
	// Search and Filtering
	SearchTaggedInvoices(ctx context.Context, in *SearchTaggedInvoicesRequest, opts ...grpc.CallOption) (*SearchTaggedInvoicesResponse, error)
	FilterTaggedInvoicesByPriority(ctx context.Context, in *FilterTaggedInvoicesByPriorityRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByPriorityResponse, error)
	FilterTaggedInvoicesByDateRange(ctx context.Context, in *FilterTaggedInvoicesByDateRangeRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByDateRangeResponse, error)
	FilterTaggedInvoicesByAmount(ctx context.Context, in *FilterTaggedInvoicesByAmountRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByAmountResponse, error)
	// Tagged Invoice Actions
	MarkTaggedInvoiceAsViewed(ctx context.Context, in *MarkTaggedInvoiceAsViewedRequest, opts ...grpc.CallOption) (*MarkTaggedInvoiceAsViewedResponse, error)
	SetInvoicePaymentReminder(ctx context.Context, in *SetInvoicePaymentReminderRequest, opts ...grpc.CallOption) (*SetInvoicePaymentReminderResponse, error)
	RequestTaggedInvoiceDetails(ctx context.Context, in *RequestTaggedInvoiceDetailsRequest, opts ...grpc.CallOption) (*RequestTaggedInvoiceDetailsResponse, error)
	GetInvoicePaymentNotifications(ctx context.Context, in *GetInvoicePaymentNotificationsRequest, opts ...grpc.CallOption) (*GetInvoicePaymentNotificationsResponse, error)
	// Status Management
	UpdateTaggedInvoiceStatus(ctx context.Context, in *UpdateTaggedInvoiceStatusRequest, opts ...grpc.CallOption) (*UpdateTaggedInvoiceStatusResponse, error)
	DeleteTaggedInvoice(ctx context.Context, in *DeleteTaggedInvoiceRequest, opts ...grpc.CallOption) (*DeleteTaggedInvoiceResponse, error)
	// Bulk Operations
	MarkMultipleInvoicesAsViewed(ctx context.Context, in *MarkMultipleInvoicesAsViewedRequest, opts ...grpc.CallOption) (*MarkMultipleInvoicesAsViewedResponse, error)
	BulkSetPaymentReminders(ctx context.Context, in *BulkSetPaymentRemindersRequest, opts ...grpc.CallOption) (*BulkSetPaymentRemindersResponse, error)
	// Statistics
	GetTaggedInvoiceStatistics(ctx context.Context, in *GetTaggedInvoiceStatisticsRequest, opts ...grpc.CallOption) (*GetTaggedInvoiceStatisticsResponse, error)
}

type taggedInvoiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaggedInvoiceServiceClient(cc grpc.ClientConnInterface) TaggedInvoiceServiceClient {
	return &taggedInvoiceServiceClient{cc}
}

func (c *taggedInvoiceServiceClient) GetTaggedInvoices(ctx context.Context, in *GetTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetTaggedInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaggedInvoicesResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetTaggedInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetTaggedInvoicesByStatus(ctx context.Context, in *GetTaggedInvoicesByStatusRequest, opts ...grpc.CallOption) (*GetTaggedInvoicesByStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaggedInvoicesByStatusResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetTaggedInvoicesByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetTaggedInvoiceById(ctx context.Context, in *GetTaggedInvoiceByIdRequest, opts ...grpc.CallOption) (*GetTaggedInvoiceByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaggedInvoiceByIdResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetTaggedInvoiceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetOverdueTaggedInvoices(ctx context.Context, in *GetOverdueTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetOverdueTaggedInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverdueTaggedInvoicesResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetOverdueTaggedInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetUpcomingTaggedInvoices(ctx context.Context, in *GetUpcomingTaggedInvoicesRequest, opts ...grpc.CallOption) (*GetUpcomingTaggedInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpcomingTaggedInvoicesResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetUpcomingTaggedInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) SearchTaggedInvoices(ctx context.Context, in *SearchTaggedInvoicesRequest, opts ...grpc.CallOption) (*SearchTaggedInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTaggedInvoicesResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_SearchTaggedInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) FilterTaggedInvoicesByPriority(ctx context.Context, in *FilterTaggedInvoicesByPriorityRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByPriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterTaggedInvoicesByPriorityResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_FilterTaggedInvoicesByPriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) FilterTaggedInvoicesByDateRange(ctx context.Context, in *FilterTaggedInvoicesByDateRangeRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByDateRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterTaggedInvoicesByDateRangeResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_FilterTaggedInvoicesByDateRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) FilterTaggedInvoicesByAmount(ctx context.Context, in *FilterTaggedInvoicesByAmountRequest, opts ...grpc.CallOption) (*FilterTaggedInvoicesByAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterTaggedInvoicesByAmountResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_FilterTaggedInvoicesByAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) MarkTaggedInvoiceAsViewed(ctx context.Context, in *MarkTaggedInvoiceAsViewedRequest, opts ...grpc.CallOption) (*MarkTaggedInvoiceAsViewedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTaggedInvoiceAsViewedResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_MarkTaggedInvoiceAsViewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) SetInvoicePaymentReminder(ctx context.Context, in *SetInvoicePaymentReminderRequest, opts ...grpc.CallOption) (*SetInvoicePaymentReminderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInvoicePaymentReminderResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_SetInvoicePaymentReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) RequestTaggedInvoiceDetails(ctx context.Context, in *RequestTaggedInvoiceDetailsRequest, opts ...grpc.CallOption) (*RequestTaggedInvoiceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTaggedInvoiceDetailsResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_RequestTaggedInvoiceDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetInvoicePaymentNotifications(ctx context.Context, in *GetInvoicePaymentNotificationsRequest, opts ...grpc.CallOption) (*GetInvoicePaymentNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvoicePaymentNotificationsResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetInvoicePaymentNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) UpdateTaggedInvoiceStatus(ctx context.Context, in *UpdateTaggedInvoiceStatusRequest, opts ...grpc.CallOption) (*UpdateTaggedInvoiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaggedInvoiceStatusResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_UpdateTaggedInvoiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) DeleteTaggedInvoice(ctx context.Context, in *DeleteTaggedInvoiceRequest, opts ...grpc.CallOption) (*DeleteTaggedInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaggedInvoiceResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_DeleteTaggedInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) MarkMultipleInvoicesAsViewed(ctx context.Context, in *MarkMultipleInvoicesAsViewedRequest, opts ...grpc.CallOption) (*MarkMultipleInvoicesAsViewedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkMultipleInvoicesAsViewedResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_MarkMultipleInvoicesAsViewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) BulkSetPaymentReminders(ctx context.Context, in *BulkSetPaymentRemindersRequest, opts ...grpc.CallOption) (*BulkSetPaymentRemindersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkSetPaymentRemindersResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_BulkSetPaymentReminders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taggedInvoiceServiceClient) GetTaggedInvoiceStatistics(ctx context.Context, in *GetTaggedInvoiceStatisticsRequest, opts ...grpc.CallOption) (*GetTaggedInvoiceStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaggedInvoiceStatisticsResponse)
	err := c.cc.Invoke(ctx, TaggedInvoiceService_GetTaggedInvoiceStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaggedInvoiceServiceServer is the server API for TaggedInvoiceService service.
// All implementations must embed UnimplementedTaggedInvoiceServiceServer
// for forward compatibility.
type TaggedInvoiceServiceServer interface {
	// Core Tagged Invoice Operations
	GetTaggedInvoices(context.Context, *GetTaggedInvoicesRequest) (*GetTaggedInvoicesResponse, error)
	GetTaggedInvoicesByStatus(context.Context, *GetTaggedInvoicesByStatusRequest) (*GetTaggedInvoicesByStatusResponse, error)
	GetTaggedInvoiceById(context.Context, *GetTaggedInvoiceByIdRequest) (*GetTaggedInvoiceByIdResponse, error)
	GetOverdueTaggedInvoices(context.Context, *GetOverdueTaggedInvoicesRequest) (*GetOverdueTaggedInvoicesResponse, error)
	GetUpcomingTaggedInvoices(context.Context, *GetUpcomingTaggedInvoicesRequest) (*GetUpcomingTaggedInvoicesResponse, error)
	// Search and Filtering
	SearchTaggedInvoices(context.Context, *SearchTaggedInvoicesRequest) (*SearchTaggedInvoicesResponse, error)
	FilterTaggedInvoicesByPriority(context.Context, *FilterTaggedInvoicesByPriorityRequest) (*FilterTaggedInvoicesByPriorityResponse, error)
	FilterTaggedInvoicesByDateRange(context.Context, *FilterTaggedInvoicesByDateRangeRequest) (*FilterTaggedInvoicesByDateRangeResponse, error)
	FilterTaggedInvoicesByAmount(context.Context, *FilterTaggedInvoicesByAmountRequest) (*FilterTaggedInvoicesByAmountResponse, error)
	// Tagged Invoice Actions
	MarkTaggedInvoiceAsViewed(context.Context, *MarkTaggedInvoiceAsViewedRequest) (*MarkTaggedInvoiceAsViewedResponse, error)
	SetInvoicePaymentReminder(context.Context, *SetInvoicePaymentReminderRequest) (*SetInvoicePaymentReminderResponse, error)
	RequestTaggedInvoiceDetails(context.Context, *RequestTaggedInvoiceDetailsRequest) (*RequestTaggedInvoiceDetailsResponse, error)
	GetInvoicePaymentNotifications(context.Context, *GetInvoicePaymentNotificationsRequest) (*GetInvoicePaymentNotificationsResponse, error)
	// Status Management
	UpdateTaggedInvoiceStatus(context.Context, *UpdateTaggedInvoiceStatusRequest) (*UpdateTaggedInvoiceStatusResponse, error)
	DeleteTaggedInvoice(context.Context, *DeleteTaggedInvoiceRequest) (*DeleteTaggedInvoiceResponse, error)
	// Bulk Operations
	MarkMultipleInvoicesAsViewed(context.Context, *MarkMultipleInvoicesAsViewedRequest) (*MarkMultipleInvoicesAsViewedResponse, error)
	BulkSetPaymentReminders(context.Context, *BulkSetPaymentRemindersRequest) (*BulkSetPaymentRemindersResponse, error)
	// Statistics
	GetTaggedInvoiceStatistics(context.Context, *GetTaggedInvoiceStatisticsRequest) (*GetTaggedInvoiceStatisticsResponse, error)
	mustEmbedUnimplementedTaggedInvoiceServiceServer()
}

// UnimplementedTaggedInvoiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaggedInvoiceServiceServer struct{}

func (UnimplementedTaggedInvoiceServiceServer) GetTaggedInvoices(context.Context, *GetTaggedInvoicesRequest) (*GetTaggedInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaggedInvoices not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetTaggedInvoicesByStatus(context.Context, *GetTaggedInvoicesByStatusRequest) (*GetTaggedInvoicesByStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaggedInvoicesByStatus not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetTaggedInvoiceById(context.Context, *GetTaggedInvoiceByIdRequest) (*GetTaggedInvoiceByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaggedInvoiceById not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetOverdueTaggedInvoices(context.Context, *GetOverdueTaggedInvoicesRequest) (*GetOverdueTaggedInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOverdueTaggedInvoices not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetUpcomingTaggedInvoices(context.Context, *GetUpcomingTaggedInvoicesRequest) (*GetUpcomingTaggedInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpcomingTaggedInvoices not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) SearchTaggedInvoices(context.Context, *SearchTaggedInvoicesRequest) (*SearchTaggedInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTaggedInvoices not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) FilterTaggedInvoicesByPriority(context.Context, *FilterTaggedInvoicesByPriorityRequest) (*FilterTaggedInvoicesByPriorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterTaggedInvoicesByPriority not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) FilterTaggedInvoicesByDateRange(context.Context, *FilterTaggedInvoicesByDateRangeRequest) (*FilterTaggedInvoicesByDateRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterTaggedInvoicesByDateRange not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) FilterTaggedInvoicesByAmount(context.Context, *FilterTaggedInvoicesByAmountRequest) (*FilterTaggedInvoicesByAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterTaggedInvoicesByAmount not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) MarkTaggedInvoiceAsViewed(context.Context, *MarkTaggedInvoiceAsViewedRequest) (*MarkTaggedInvoiceAsViewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTaggedInvoiceAsViewed not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) SetInvoicePaymentReminder(context.Context, *SetInvoicePaymentReminderRequest) (*SetInvoicePaymentReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInvoicePaymentReminder not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) RequestTaggedInvoiceDetails(context.Context, *RequestTaggedInvoiceDetailsRequest) (*RequestTaggedInvoiceDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTaggedInvoiceDetails not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetInvoicePaymentNotifications(context.Context, *GetInvoicePaymentNotificationsRequest) (*GetInvoicePaymentNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvoicePaymentNotifications not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) UpdateTaggedInvoiceStatus(context.Context, *UpdateTaggedInvoiceStatusRequest) (*UpdateTaggedInvoiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaggedInvoiceStatus not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) DeleteTaggedInvoice(context.Context, *DeleteTaggedInvoiceRequest) (*DeleteTaggedInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaggedInvoice not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) MarkMultipleInvoicesAsViewed(context.Context, *MarkMultipleInvoicesAsViewedRequest) (*MarkMultipleInvoicesAsViewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMultipleInvoicesAsViewed not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) BulkSetPaymentReminders(context.Context, *BulkSetPaymentRemindersRequest) (*BulkSetPaymentRemindersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkSetPaymentReminders not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) GetTaggedInvoiceStatistics(context.Context, *GetTaggedInvoiceStatisticsRequest) (*GetTaggedInvoiceStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaggedInvoiceStatistics not implemented")
}
func (UnimplementedTaggedInvoiceServiceServer) mustEmbedUnimplementedTaggedInvoiceServiceServer() {}
func (UnimplementedTaggedInvoiceServiceServer) testEmbeddedByValue()                              {}

// UnsafeTaggedInvoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaggedInvoiceServiceServer will
// result in compilation errors.
type UnsafeTaggedInvoiceServiceServer interface {
	mustEmbedUnimplementedTaggedInvoiceServiceServer()
}

func RegisterTaggedInvoiceServiceServer(s grpc.ServiceRegistrar, srv TaggedInvoiceServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaggedInvoiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaggedInvoiceService_ServiceDesc, srv)
}

func _TaggedInvoiceService_GetTaggedInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaggedInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetTaggedInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoices(ctx, req.(*GetTaggedInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetTaggedInvoicesByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaggedInvoicesByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoicesByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetTaggedInvoicesByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoicesByStatus(ctx, req.(*GetTaggedInvoicesByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetTaggedInvoiceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaggedInvoiceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoiceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetTaggedInvoiceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoiceById(ctx, req.(*GetTaggedInvoiceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetOverdueTaggedInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverdueTaggedInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetOverdueTaggedInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetOverdueTaggedInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetOverdueTaggedInvoices(ctx, req.(*GetOverdueTaggedInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetUpcomingTaggedInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpcomingTaggedInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetUpcomingTaggedInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetUpcomingTaggedInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetUpcomingTaggedInvoices(ctx, req.(*GetUpcomingTaggedInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_SearchTaggedInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTaggedInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).SearchTaggedInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_SearchTaggedInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).SearchTaggedInvoices(ctx, req.(*SearchTaggedInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_FilterTaggedInvoicesByPriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterTaggedInvoicesByPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByPriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_FilterTaggedInvoicesByPriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByPriority(ctx, req.(*FilterTaggedInvoicesByPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_FilterTaggedInvoicesByDateRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterTaggedInvoicesByDateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByDateRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_FilterTaggedInvoicesByDateRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByDateRange(ctx, req.(*FilterTaggedInvoicesByDateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_FilterTaggedInvoicesByAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterTaggedInvoicesByAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_FilterTaggedInvoicesByAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).FilterTaggedInvoicesByAmount(ctx, req.(*FilterTaggedInvoicesByAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_MarkTaggedInvoiceAsViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTaggedInvoiceAsViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).MarkTaggedInvoiceAsViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_MarkTaggedInvoiceAsViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).MarkTaggedInvoiceAsViewed(ctx, req.(*MarkTaggedInvoiceAsViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_SetInvoicePaymentReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInvoicePaymentReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).SetInvoicePaymentReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_SetInvoicePaymentReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).SetInvoicePaymentReminder(ctx, req.(*SetInvoicePaymentReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_RequestTaggedInvoiceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTaggedInvoiceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).RequestTaggedInvoiceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_RequestTaggedInvoiceDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).RequestTaggedInvoiceDetails(ctx, req.(*RequestTaggedInvoiceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetInvoicePaymentNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoicePaymentNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetInvoicePaymentNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetInvoicePaymentNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetInvoicePaymentNotifications(ctx, req.(*GetInvoicePaymentNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_UpdateTaggedInvoiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaggedInvoiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).UpdateTaggedInvoiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_UpdateTaggedInvoiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).UpdateTaggedInvoiceStatus(ctx, req.(*UpdateTaggedInvoiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_DeleteTaggedInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaggedInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).DeleteTaggedInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_DeleteTaggedInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).DeleteTaggedInvoice(ctx, req.(*DeleteTaggedInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_MarkMultipleInvoicesAsViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkMultipleInvoicesAsViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).MarkMultipleInvoicesAsViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_MarkMultipleInvoicesAsViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).MarkMultipleInvoicesAsViewed(ctx, req.(*MarkMultipleInvoicesAsViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_BulkSetPaymentReminders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkSetPaymentRemindersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).BulkSetPaymentReminders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_BulkSetPaymentReminders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).BulkSetPaymentReminders(ctx, req.(*BulkSetPaymentRemindersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaggedInvoiceService_GetTaggedInvoiceStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaggedInvoiceStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoiceStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaggedInvoiceService_GetTaggedInvoiceStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggedInvoiceServiceServer).GetTaggedInvoiceStatistics(ctx, req.(*GetTaggedInvoiceStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaggedInvoiceService_ServiceDesc is the grpc.ServiceDesc for TaggedInvoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaggedInvoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TaggedInvoiceService",
	HandlerType: (*TaggedInvoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaggedInvoices",
			Handler:    _TaggedInvoiceService_GetTaggedInvoices_Handler,
		},
		{
			MethodName: "GetTaggedInvoicesByStatus",
			Handler:    _TaggedInvoiceService_GetTaggedInvoicesByStatus_Handler,
		},
		{
			MethodName: "GetTaggedInvoiceById",
			Handler:    _TaggedInvoiceService_GetTaggedInvoiceById_Handler,
		},
		{
			MethodName: "GetOverdueTaggedInvoices",
			Handler:    _TaggedInvoiceService_GetOverdueTaggedInvoices_Handler,
		},
		{
			MethodName: "GetUpcomingTaggedInvoices",
			Handler:    _TaggedInvoiceService_GetUpcomingTaggedInvoices_Handler,
		},
		{
			MethodName: "SearchTaggedInvoices",
			Handler:    _TaggedInvoiceService_SearchTaggedInvoices_Handler,
		},
		{
			MethodName: "FilterTaggedInvoicesByPriority",
			Handler:    _TaggedInvoiceService_FilterTaggedInvoicesByPriority_Handler,
		},
		{
			MethodName: "FilterTaggedInvoicesByDateRange",
			Handler:    _TaggedInvoiceService_FilterTaggedInvoicesByDateRange_Handler,
		},
		{
			MethodName: "FilterTaggedInvoicesByAmount",
			Handler:    _TaggedInvoiceService_FilterTaggedInvoicesByAmount_Handler,
		},
		{
			MethodName: "MarkTaggedInvoiceAsViewed",
			Handler:    _TaggedInvoiceService_MarkTaggedInvoiceAsViewed_Handler,
		},
		{
			MethodName: "SetInvoicePaymentReminder",
			Handler:    _TaggedInvoiceService_SetInvoicePaymentReminder_Handler,
		},
		{
			MethodName: "RequestTaggedInvoiceDetails",
			Handler:    _TaggedInvoiceService_RequestTaggedInvoiceDetails_Handler,
		},
		{
			MethodName: "GetInvoicePaymentNotifications",
			Handler:    _TaggedInvoiceService_GetInvoicePaymentNotifications_Handler,
		},
		{
			MethodName: "UpdateTaggedInvoiceStatus",
			Handler:    _TaggedInvoiceService_UpdateTaggedInvoiceStatus_Handler,
		},
		{
			MethodName: "DeleteTaggedInvoice",
			Handler:    _TaggedInvoiceService_DeleteTaggedInvoice_Handler,
		},
		{
			MethodName: "MarkMultipleInvoicesAsViewed",
			Handler:    _TaggedInvoiceService_MarkMultipleInvoicesAsViewed_Handler,
		},
		{
			MethodName: "BulkSetPaymentReminders",
			Handler:    _TaggedInvoiceService_BulkSetPaymentReminders_Handler,
		},
		{
			MethodName: "GetTaggedInvoiceStatistics",
			Handler:    _TaggedInvoiceService_GetTaggedInvoiceStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tagged_invoice.proto",
}
