// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: tx_file.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for GetUserTxFileUrl
type GetUserTxFileUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTxFileUrlRequest) Reset() {
	*x = GetUserTxFileUrlRequest{}
	mi := &file_tx_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTxFileUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTxFileUrlRequest) ProtoMessage() {}

func (x *GetUserTxFileUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTxFileUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUserTxFileUrlRequest) Descriptor() ([]byte, []int) {
	return file_tx_file_proto_rawDescGZIP(), []int{0}
}

// Response message for GetUserTxFileUrl
type GetUserTxFileUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Public HTTPS URL to the transaction file.
	// Requires the GCS object to be publicly readable.
	PublicFileUrl string `protobuf:"bytes,1,opt,name=public_file_url,json=publicFileUrl,proto3" json:"public_file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTxFileUrlResponse) Reset() {
	*x = GetUserTxFileUrlResponse{}
	mi := &file_tx_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTxFileUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTxFileUrlResponse) ProtoMessage() {}

func (x *GetUserTxFileUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTxFileUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUserTxFileUrlResponse) Descriptor() ([]byte, []int) {
	return file_tx_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserTxFileUrlResponse) GetPublicFileUrl() string {
	if x != nil {
		return x.PublicFileUrl
	}
	return ""
}

var File_tx_file_proto protoreflect.FileDescriptor

const file_tx_file_proto_rawDesc = "" +
	"\n" +
	"\rtx_file.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17GetUserTxFileUrlRequest\"B\n" +
	"\x18GetUserTxFileUrlResponse\x12&\n" +
	"\x0fpublic_file_url\x18\x01 \x01(\tR\rpublicFileUrl2|\n" +
	"\rTxFileService\x12k\n" +
	"\x10GetUserTxFileUrl\x12\x1b.pb.GetUserTxFileUrlRequest\x1a\x1c.pb.GetUserTxFileUrlResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/users/txfile/urlB\x11Z\x0flazervaultGo/pbb\x06proto3"

var (
	file_tx_file_proto_rawDescOnce sync.Once
	file_tx_file_proto_rawDescData []byte
)

func file_tx_file_proto_rawDescGZIP() []byte {
	file_tx_file_proto_rawDescOnce.Do(func() {
		file_tx_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_file_proto_rawDesc), len(file_tx_file_proto_rawDesc)))
	})
	return file_tx_file_proto_rawDescData
}

var file_tx_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tx_file_proto_goTypes = []any{
	(*GetUserTxFileUrlRequest)(nil),  // 0: pb.GetUserTxFileUrlRequest
	(*GetUserTxFileUrlResponse)(nil), // 1: pb.GetUserTxFileUrlResponse
}
var file_tx_file_proto_depIdxs = []int32{
	0, // 0: pb.TxFileService.GetUserTxFileUrl:input_type -> pb.GetUserTxFileUrlRequest
	1, // 1: pb.TxFileService.GetUserTxFileUrl:output_type -> pb.GetUserTxFileUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tx_file_proto_init() }
func file_tx_file_proto_init() {
	if File_tx_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_file_proto_rawDesc), len(file_tx_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_file_proto_goTypes,
		DependencyIndexes: file_tx_file_proto_depIdxs,
		MessageInfos:      file_tx_file_proto_msgTypes,
	}.Build()
	File_tx_file_proto = out.File
	file_tx_file_proto_goTypes = nil
	file_tx_file_proto_depIdxs = nil
}
